/* Chunks: each word as it is actually said.

   Nobody says "hambre". They say "tengo hambre". A word learnt on its own
   has to be assembled into speech on the spot, which is slow and is where it
   goes missing; a word learnt inside the phrase it usually lives in comes out
   whole. So the commonest words carry one short, everyday phrase, and that
   phrase is what the teaching card leads with and what the verdict shows.

   Covers the core of the teaching order, the words that make up most of
   everyday speech. Set phrases (por favor, ¿me regala?) are chunks already
   and need nothing here. Colombian usage where it differs.

   Shape: { [wordId]: [spanish, english] }. The word itself is in {braces},
   in whatever form the phrase needs, as the sentences do. tests/test-chunks
   checks every braced form really is a form of its word, and that every
   other word in the phrase is one the bank knows, so each can be tapped.
*/
window.CHUNKS = {
  // The verbs everything hangs off
  ser: ["{soy} inglés", "I'm English"],
  estar: ["¿cómo {estás}?", "how are you?"],
  tener: ["{tengo} hambre", "I'm hungry"],
  hacer: ["¿qué {haces}?", "what are you doing?"],
  ir: ["{voy} a la playa", "I'm going to the beach"],
  poder: ["¿{puedo} pagar con tarjeta?", "can I pay by card?"],
  querer: ["{quiero} un café", "I want a coffee"],
  hay: ["no {hay} problema", "there's no problem"],
  decir: ["¿cómo se {dice}?", "how do you say it?"],
  ver: ["nos {vemos} mañana", "see you tomorrow"],
  dar: ["me {da} igual", "I don't mind"],
  saber: ["no {sé}", "I don't know"],
  venir: ["¿{vienes} conmigo?", "are you coming with me?"],
  salir: ["{salgo} a las ocho", "I leave at eight"],
  llegar: ["{llego} tarde", "I'm late, I'm arriving late"],
  hablar: ["{hablo} un poco de español", "I speak a little Spanish"],
  comer: ["vamos a {comer}", "let's eat"],
  beber: ["algo de {beber}", "something to drink"],
  vivir: ["{vivo} en el centro", "I live in the centre"],
  necesitar: ["{necesito} ayuda", "I need help"],
  pensar: ["{pienso} que sí", "I think so"],
  creer: ["{creo} que no", "I don't think so"],
  gustar: ["me {gusta} mucho", "I like it a lot"],
  pedir: ["voy a {pedir} la cuenta", "I'm going to ask for the bill"],
  esperar: ["{espera} un momento", "wait a moment"],
  poner: ["¿dónde lo {pongo}?", "where do I put it?"],
  llevar: ["para {llevar}", "to take away"],
  dejar: ["¿me {dejas} pasar?", "can you let me past?"],
  pasar: ["¿qué {pasó}?", "what happened?"],
  quedar: ["¿dónde {queda}?", "where is it?"],
  tomar: ["¿qué vas a {tomar}?", "what are you having?"],
  llamar: ["te {llamo} luego", "I'll call you later"],
  conocer: ["quiero {conocer} la ciudad", "I want to see the city"],
  entrar: ["¿puedo {entrar}?", "can I come in?"],
  llamarse: ["me {llamo} Ana", "my name is Ana"],

  // Little words
  de: ["la casa {de} mi madre", "my mother's house"],
  en: ["{en} la casa", "in the house, at home"],
  a: ["voy {a} la tienda", "I'm going to the shop"],
  no: ["{no} sé", "I don't know"],
  y: ["tú {y} yo", "you and me"],
  que: ["¿{qué} es eso?", "what's that?"],
  "si-cond": ["{si} quieres", "if you want"],
  o: ["¿café {o} té?", "coffee or tea?"],
  pero: ["sí, {pero} no ahora", "yes, but not now"],
  porque: ["{porque} estoy cansado", "because I'm tired"],
  muy: ["{muy} bien", "very well"],
  mas: ["{más} o menos", "more or less, so-so"],
  mucho: ["{mucho} gusto", "nice to meet you"],
  yo: ["{yo} también", "me too"],
  tu: ["¿cuál es {tu} nombre?", "what's your name?"],
  "el-pron": ["{él} es mi amigo", "he's my friend"],
  ella: ["{ella} es de aquí", "she's from here"],
  nosotros: ["{nosotros} vamos", "we're going"],
  ustedes: ["¿{ustedes} quieren algo?", "do you all want anything?"],
  usted: ["¿y {usted}?", "and you?"],
  con: ["café {con} leche", "coffee with milk"],
  como: ["¿{cómo} estás?", "how are you?"],
  bien: ["muy {bien}, gracias", "very well, thanks"],
  mal: ["no está {mal}", "it's not bad"],
  despacio: ["más {despacio}, por favor", "more slowly, please"],
  donde: ["¿{dónde} está el baño?", "where's the toilet?"],
  cuando: ["¿{cuándo} llegas?", "when do you arrive?"],
  quien: ["¿{quién} es?", "who is it?"],
  "por-que": ["¿{por qué} no?", "why not?"],
  cuanto: ["¿{cuánto} cuesta?", "how much is it?"],
  cuantos: ["¿{cuántos} años tienes?", "how old are you?"],
  adonde: ["¿{adónde} vas?", "where are you going?"],
  nombre: ["mi {nombre} es Ana", "my name is Ana"],
  vida: ["así es la {vida}", "that's life"],
  ti: ["para {ti}", "for you"],
  conmigo: ["¿vienes {conmigo}?", "are you coming with me?"],
  contigo: ["voy {contigo}", "I'll go with you"],
  les: ["{les} gusta bailar", "they like dancing"],
  ellas: ["{ellas} son mis amigas", "they're my friends"],
  nosotras: ["{nosotras} también", "us too"],
  mio: ["es {mío}", "it's mine"],
  tuyo: ["¿es {tuyo}?", "is it yours?"],
  suyo: ["no es {suyo}", "it's not his"],
  tan: ["¡qué {tan} bonito!", "how lovely!"],
  ni: ["{ni} idea", "no idea"],
  pues: ["{pues} sí", "well, yes"],
  luego: ["hasta {luego}", "see you later"],
  pronto: ["hasta {pronto}", "see you soon"],
  igual: ["me da {igual}", "I don't mind"],
  "otra-vez": ["{otra vez}, por favor", "again, please"],
  "a-veces": ["{a veces} voy a la playa", "sometimes I go to the beach"],
  cual: ["¿{cuál} quieres?", "which one do you want?"],
  esto: ["¿qué es {esto}?", "what's this?"],
  eso: ["{eso} es", "that's it, exactly"],
  este: ["{este} fin de semana", "this weekend"],
  ese: ["{ese} carro", "that car"],
  aqui: ["{aquí} está", "here it is"],
  alli: ["{allí} está", "there it is"],
  cerca: ["{cerca} de aquí", "near here"],
  lejos: ["queda {lejos}", "it's a long way"],
  arriba: ["está {arriba}", "it's upstairs"],
  abajo: ["te espero {abajo}", "I'll wait for you downstairs"],
  afuera: ["vamos {afuera}", "let's go outside"],
  adentro: ["está {adentro}", "it's inside"],
  enfrente: ["{enfrente} del banco", "opposite the bank"],
  izquierda: ["a la {izquierda}", "on the left"],
  derecha: ["a la {derecha}", "on the right"],
  lo: ["{lo} siento", "I'm sorry"],
  se: ["¿cómo {se} dice?", "how do you say it?"],
  me: ["{me} gusta", "I like it"],
  te: ["{te} llamo luego", "I'll call you later"],
  le: ["{le} digo", "I'll tell him"],
  nos: ["{nos} vemos", "see you"],
  su: ["¿es {su} carro?", "is it your car?"],
  mi: ["{mi} casa", "my house"],
  nuestro: ["{nuestro} amigo", "our friend"],

  // Time
  hoy: ["{hoy} no", "not today"],
  manana: ["hasta {mañana}", "see you tomorrow"],
  ayer: ["{ayer} por la noche", "last night"],
  ahora: ["{ahora} no puedo", "I can't right now"],
  dia: ["buenos {días}", "good morning"],
  noche: ["por la {noche}", "at night"],
  semana: ["la próxima {semana}", "next week"],
  mes: ["el {mes} pasado", "last month"],
  ano: ["¿cuántos {años} tienes?", "how old are you?"],
  hora: ["¿qué {hora} es?", "what time is it?"],
  minuto: ["un {minuto}", "one minute"],
  tiempo: ["no tengo {tiempo}", "I haven't got time"],
  vez: ["otra {vez}", "again"],
  tarde: ["por la {tarde}", "in the afternoon"],
  temprano: ["muy {temprano}", "very early"],
  siempre: ["como {siempre}", "as always"],
  nunca: ["casi {nunca}", "hardly ever"],
  ya: ["{ya} voy", "I'm coming, on my way"],
  todavia: ["{todavía} no", "not yet"],
  antes: ["{antes} de comer", "before eating"],
  despues: ["{después} de clase", "after class"],
  proximo: ["la {próxima} vez", "next time"],
  pasado: ["el año {pasado}", "last year"],
  lunes: ["el {lunes}", "on Monday"],
  martes: ["los {martes}", "on Tuesdays"],
  miercoles: ["hasta el {miércoles}", "see you Wednesday"],
  jueves: ["el {jueves} por la noche", "on Thursday night"],
  viernes: ["el {viernes} salimos", "we're going out on Friday"],
  sabado: ["el {sábado} por la mañana", "on Saturday morning"],
  domingo: ["los {domingos} no trabajo", "I don't work on Sundays"],

  // Numbers
  uno: ["{uno} más", "one more"],
  dos: ["{dos} cervezas, por favor", "two beers, please"],
  tres: ["a las {tres}", "at three"],
  cuatro: ["somos {cuatro}", "there are four of us"],
  cinco: ["{cinco} minutos", "five minutes"],
  seis: ["a las {seis} de la tarde", "at six in the evening"],
  siete: ["{siete} días", "seven days"],
  ocho: ["a las {ocho}", "at eight"],
  nueve: ["a las {nueve}", "at nine"],
  diez: ["{diez} minutos", "ten minutes"],
  veinte: ["{veinte} mil", "twenty thousand"],
  cien: ["{cien} mil", "a hundred thousand"],
  mil: ["{mil} gracias", "thanks a million"],
  primero: ["la {primera} vez", "the first time"],
  ultimo: ["la {última} vez", "the last time"],
  medio: ["y {media}", "half past"],
  segundo: ["un {segundo}", "one second"],
  mitad: ["la {mitad}", "half of it"],
  par: ["un {par} de días", "a couple of days"],
  tercero: ["el {tercer} piso", "the third floor"],

  // People
  hombre: ["un {hombre} alto", "a tall man"],
  mujer: ["mi {mujer}", "my wife"],
  gente: ["mucha {gente}", "lots of people"],
  persona: ["una {persona} más", "one more person"],
  amigo: ["un {amigo} mío", "a friend of mine"],
  familia: ["mi {familia}", "my family"],
  nino: ["los {niños}", "the children"],
  nina: ["una {niña} pequeña", "a little girl"],
  madre: ["mi {madre}", "my mother"],
  padre: ["mis {padres}", "my parents"],
  hijo: ["¿tienes {hijos}?", "have you got children?"],
  hermano: ["mi {hermano} mayor", "my older brother"],
  hermana: ["mi {hermana} pequeña", "my little sister"],
  senor: ["buenos días, {señor}", "good morning, sir"],
  senora: ["gracias, {señora}", "thank you, madam"],
  esposo: ["mi {esposo}", "my husband"],
  novio: ["mi {novia}", "my girlfriend"],
  abuelo: ["mis {abuelos}", "my grandparents"],
  vecino: ["el {vecino} de arriba", "the upstairs neighbour"],
  ellos: ["{ellos} vienen mañana", "they're coming tomorrow"],

  // Food and drink
  agua: ["un vaso de {agua}", "a glass of water"],
  comida: ["la {comida} está lista", "the food's ready"],
  pan: ["{pan} con queso", "bread and cheese"],
  almuerzo: ["la hora del {almuerzo}", "lunchtime"],
  desayuno: ["¿a qué hora es el {desayuno}?", "what time is breakfast?"],
  cena: ["¿qué hay de {cena}?", "what's for dinner?"],
  carne: ["no como {carne}", "I don't eat meat"],
  pollo: ["arroz con {pollo}", "chicken and rice"],
  arroz: ["{arroz} con pollo", "chicken and rice"],
  huevo: ["arroz con {huevo}", "rice with egg"],
  fruta: ["un jugo de {fruta}", "a fruit juice"],
  leche: ["café con {leche}", "white coffee"],
  cerveza: ["una {cerveza} fría", "a cold beer"],
  jugo: ["un {jugo} de naranja", "an orange juice"],
  sal: ["sin {sal}", "without salt"],
  azucar: ["sin {azúcar}, por favor", "no sugar, please"],
  sopa: ["una {sopa} de pollo", "a chicken soup"],
  plato: ["el {plato} del día", "the dish of the day"],
  mesa: ["una {mesa} para dos", "a table for two"],
  tocineta: ["huevos con {tocineta}", "bacon and eggs"],
  tinto: ["¿me regala un {tinto}?", "could I have a black coffee?"],
  hambre: ["tengo {hambre}", "I'm hungry"],
  cocinar: ["me gusta {cocinar}", "I like cooking"],

  // Money and shops
  dinero: ["no tengo {dinero}", "I haven't got any money"],
  plata: ["no tengo {plata}", "I'm skint"],
  precio: ["¿cuál es el {precio}?", "what's the price?"],
  cuenta: ["la {cuenta}, por favor", "the bill, please"],
  tienda: ["voy a la {tienda}", "I'm going to the shop"],
  mercado: ["en el {mercado}", "at the market"],
  caro: ["muy {caro}", "very expensive"],
  barato: ["más {barato}", "cheaper"],
  comprar: ["voy a {comprar} pan", "I'm going to buy bread"],
  vender: ["se {vende}", "for sale"],
  pagar: ["¿puedo {pagar} con tarjeta?", "can I pay by card?"],
  pinta: ["una {pinta} de cerveza", "a pint of beer"],
  cambio: ["¿tiene {cambio}?", "have you got change?"],

  // Places and getting around
  casa: ["en {casa}", "at home"],
  calle: ["en la {calle}", "in the street"],
  ciudad: ["el centro de la {ciudad}", "the city centre"],
  centro: ["en el {centro}", "in the centre"],
  pais: ["un {país} bonito", "a beautiful country"],
  mundo: ["todo el {mundo}", "everyone"],
  lugar: ["un {lugar} bonito", "a nice place"],
  camino: ["en {camino}", "on the way"],
  salida: ["¿dónde está la {salida}?", "where's the exit?"],
  carro: ["en {carro}", "by car"],
  bus: ["en {bus}", "by bus"],
  taxi: ["voy en {taxi}", "I'm going by taxi"],
  avion: ["en {avión}", "by plane"],
  viaje: ["¡buen {viaje}!", "have a good trip!"],
  hotel: ["el {hotel} está cerca", "the hotel's nearby"],
  aeropuerto: ["al {aeropuerto}, por favor", "to the airport, please"],
  maleta: ["mi {maleta}", "my suitcase"],
  boleto: ["dos {boletos}, por favor", "two tickets, please"],
  caminar: ["vamos a {caminar}", "let's walk"],
  viajar: ["me gusta {viajar}", "I like travelling"],
  playa: ["en la {playa}", "on the beach"],
  montana: ["en la {montaña}", "in the mountains"],
  rio: ["al lado del {río}", "next to the river"],

  // Home
  puerta: ["cierra la {puerta}", "shut the door"],
  ventana: ["abre la {ventana}", "open the window"],
  llave: ["no tengo la {llave}", "I haven't got the key"],
  cama: ["me voy a la {cama}", "I'm off to bed"],
  silla: ["¿está libre esta {silla}?", "is this chair free?"],
  cocina: ["en la {cocina}", "in the kitchen"],
  habitacion: ["una {habitación} doble", "a double room"],
  dormitorio: ["el {dormitorio} está arriba", "the bedroom is upstairs"],
  bano: ["¿dónde está el {baño}?", "where's the toilet?"],
  ropa: ["lavar la {ropa}", "to do the washing"],
  luz: ["se fue la {luz}", "the power's gone off"],
  caneca: ["a la {caneca}", "in the bin"],
  bolsa: ["¿quiere {bolsa}?", "do you want a bag?"],
  alquilar: ["{alquilar} un carro", "to hire a car"],
  dormir: ["voy a {dormir}", "I'm going to sleep"],

  // Describing things
  bueno: ["muy {bueno}", "very good"],
  malo: ["no es {malo}", "it's not bad"],
  grande: ["una casa {grande}", "a big house"],
  pequeno: ["un poco {pequeño}", "a bit small"],
  nuevo: ["¿qué hay de {nuevo}?", "what's new?"],
  viejo: ["un amigo {viejo}", "an old friend"],
  joven: ["muy {joven}", "very young"],
  bonito: ["¡qué {bonito}!", "how lovely!"],
  feo: ["¡qué {feo}!", "how ugly!"],
  facil: ["es {fácil}", "it's easy"],
  dificil: ["es muy {difícil}", "it's very hard"],
  rapido: ["muy {rápido}", "very fast"],
  lento: ["el internet está {lento}", "the internet is slow"],
  caliente: ["agua {caliente}", "hot water"],
  frio: ["hace {frío}", "it's cold"],
  limpio: ["está {limpio}", "it's clean"],
  sucio: ["está {sucio}", "it's dirty"],
  largo: ["un día {largo}", "a long day"],
  corto: ["un viaje {corto}", "a short trip"],
  alto: ["muy {alto}", "very tall"],
  bajo: ["más {bajo}, por favor", "lower, please"],
  fuerte: ["un café {fuerte}", "a strong coffee"],
  debil: ["me siento {débil}", "I feel weak"],
  lleno: ["estoy {lleno}", "I'm full"],
  abierto: ["está {abierto}", "it's open"],
  cerrado: ["está {cerrado}", "it's closed"],
  listo: ["¿{listo}?", "ready?"],
  mismo: ["lo {mismo}", "the same"],
  diferente: ["es {diferente}", "it's different"],
  mejor: ["{mejor} así", "better like that"],
  peor: ["cada vez {peor}", "worse and worse"],
  importante: ["es muy {importante}", "it's really important"],
  posible: ["no es {posible}", "it isn't possible"],
  seguro: ["¿estás {seguro}?", "are you sure?"],
  rojo: ["el vino {rojo}", "the red wine"],
  verde: ["la casa {verde}", "the green house"],
  azul: ["el cielo {azul}", "the blue sky"],
  negro: ["café {negro}", "black coffee"],
  blanco: ["arroz {blanco}", "plain rice"],
  amarillo: ["un taxi {amarillo}", "a yellow taxi"],

  // How you are
  feliz: ["¡{feliz} cumpleaños!", "happy birthday!"],
  triste: ["estoy {triste}", "I'm sad"],
  cansado: ["estoy muy {cansado}", "I'm really tired"],
  contento: ["estoy {contento}", "I'm happy"],
  enojado: ["¿estás {enojado}?", "are you angry?"],
  preocupado: ["no estés {preocupado}", "don't worry"],
  nervioso: ["estoy {nervioso}", "I'm nervous"],
  aburrido: ["estoy {aburrido}", "I'm bored"],
  enfermo: ["estoy {enfermo}", "I'm ill"],
  cabeza: ["me duele la {cabeza}", "I've got a headache"],
  mano: ["con la {mano}", "by hand"],
  ojo: ["¡{ojo}!", "watch out!"],
  pie: ["a {pie}", "on foot"],
  dolor: ["tengo {dolor} de cabeza", "I've got a headache"],
  doler: ["me {duele} aquí", "it hurts here"],
  medico: ["necesito un {médico}", "I need a doctor"],

  // Work and study
  trabajo: ["voy al {trabajo}", "I'm going to work"],
  trabajar: ["tengo que {trabajar}", "I have to work"],
  estudiar: ["{estudio} español", "I'm studying Spanish"],
  oficina: ["en la {oficina}", "at the office"],
  empresa: ["una {empresa} pequeña", "a small company"],
  reunion: ["tengo una {reunión}", "I've got a meeting"],
  jefe: ["mi {jefe}", "my boss"],
  clase: ["después de {clase}", "after class"],
  palabra: ["¿qué significa esta {palabra}?", "what does this word mean?"],
  pregunta: ["tengo una {pregunta}", "I've got a question"],
  problema: ["no hay {problema}", "no problem"],
  cosa: ["otra {cosa}", "something else"],

  // Everyday verbs
  aprender: ["quiero {aprender} español", "I want to learn Spanish"],
  empezar: ["¿a qué hora {empieza}?", "what time does it start?"],
  terminar: ["ya {terminé}", "I've finished"],
  seguir: ["{siga} derecho", "go straight on"],
  volver: ["ya {vuelvo}", "I'll be right back"],
  parecer: ["me {parece} bien", "sounds good to me"],
  sentir: ["lo {siento}", "I'm sorry"],
  entender: ["no {entiendo}", "I don't understand"],
  escribir: ["¿cómo se {escribe}?", "how do you spell it?"],
  leer: ["me gusta {leer}", "I like reading"],
  escuchar: ["{escucha}", "listen"],
  mirar: ["solo {miro}, gracias", "just looking, thanks"],
  abrir: ["¿a qué hora {abren}?", "what time do you open?"],
  cerrar: ["¿a qué hora {cierran}?", "what time do you close?"],
  ayudar: ["¿me {ayudas}?", "can you help me?"],
  jugar: ["{jugar} fútbol", "to play football"],
  correr: ["salgo a {correr}", "I go running"],
  buscar: ["{busco} el baño", "I'm looking for the toilet"],
  encontrar: ["no {encuentro} mi llave", "I can't find my key"],
  conseguir: ["¿dónde {consigo} un taxi?", "where can I get a taxi?"],
  usar: ["¿puedo {usar} el baño?", "can I use the toilet?"],
  tocar: ["te {toca}", "it's your turn"],
  deber: ["¿cuánto le {debo}?", "how much do I owe you?"],
  traer: ["¿me {trae} la cuenta?", "could you bring me the bill?"],
  prestar: ["¿me {prestas} tu carro?", "can you lend me your car?"],
  intentar: ["voy a {intentar}", "I'll try"],
  ganar: ["{ganamos}", "we won"],
  perder: ["{perdí} el bus", "I missed the bus"],
  cambiar: ["¿puedo {cambiar} esto?", "can I change this?"],
  mandar: ["te {mando} un mensaje", "I'll send you a message"],
  preguntar: ["¿te puedo {preguntar} algo?", "can I ask you something?"],
  contestar: ["no {contesta}", "there's no answer"],
  olvidar: ["se me {olvidó}", "I forgot"],
  recordar: ["no {recuerdo}", "I don't remember"],
  llorar: ["no {llores}", "don't cry"],
  reir: ["me hace {reír}", "it makes me laugh"],
  coger: ["{coger} un taxi", "to get a taxi"],

  // Weather and outdoors
  clima: ["¿cómo está el {clima}?", "what's the weather like?"],
  lluvia: ["con esta {lluvia}", "in this rain"],
  sol: ["hace {sol}", "it's sunny"],
  arbol: ["debajo del {árbol}", "under the tree"],
  perro: ["tengo un {perro}", "I've got a dog"],
  gato: ["el {gato} negro", "the black cat"],

  // Glue
  tambien: ["yo {también}", "me too"],
  tampoco: ["yo {tampoco}", "me neither"],
  poco: ["un {poco}", "a little"],
  menos: ["más o {menos}", "more or less, so-so"],
  tanto: ["no {tanto}", "not so much"],
  solo: ["{solo} un poco", "just a little"],
  asi: ["{así} es", "that's right"],
  claro: ["¡{claro}!", "of course!"],
  entonces: ["¿{entonces} qué?", "so what?"],
  aunque: ["{aunque} no quiero", "even though I don't want to"],
  mientras: ["{mientras} tanto", "meanwhile"],
  sin: ["{sin} problema", "no problem"],
  sobre: ["{sobre} la mesa", "on the table"],
  entre: ["{entre} semana", "during the week"],
  hasta: ["{hasta} luego", "see you later"],
  durante: ["{durante} el día", "during the day"],
  desde: ["{desde} cuándo", "since when"],
  para: ["{para} llevar", "to take away"],
};
