/* Grammar: the points that trip up English speakers, each with a short
   lesson and a drill.

   Chosen from what Spanish teachers and learner guides keep listing as the
   mistakes English speakers make, and ordered roughly the way the Instituto
   Cervantes curriculum orders A1 and A2: ser and estar first, the subjunctive
   last. Every lesson is the same shape:

     explain    a few short paragraphs, the rule as a learner can use it
     examples   [Spanish, English] pairs, each one tappable and playable
     mistake    the classic wrong version and the right one
     items      the drill: a sentence with ___ where the choice goes

   A drill item gives two to four options and says why the answer is right.
   An option of "—" means nothing goes in the gap at all, which is how the
   personal a is drilled: the question is whether it is there.

   Latin American throughout: ustedes, never vosotros. British English in
   every English line, since the English is read, and sometimes typed. */

window.GRAMMAR = {
  lessons: [
    {
      id: "ser-estar",
      title: "Ser and estar",
      short: "ser / estar",
      blurb: "Two verbs for to be, and the mistake every learner makes first.",
      explain: [
        "Spanish splits to be in two. ser is for what something is: who someone is, what they do, where they are from, what something is made of, the time and the date.",
        "estar is for how something is and where it is: moods and feelings, health, a state that could change, and location. Even a place that will never move takes estar: Bogotá está en Colombia.",
        "A handful of adjectives change meaning with the verb. Es aburrido is he is boring; está aburrido is he is bored. Es listo is clever; está listo is ready.",
      ],
      examples: [
        ["Soy ingeniero.", "I am an engineer."],
        ["Estoy cansado.", "I am tired."],
        ["Mi casa está cerca del parque.", "My house is near the park."],
        ["La fiesta es el sábado.", "The party is on Saturday."],
      ],
      mistake: ["Soy aburrido en esta clase.", "Estoy aburrido en esta clase.", "I am bored, right now, not a boring person."],
      items: [
        { es: "Mi hermano ___ médico.", en: "My brother is a doctor.", options: ["es", "está"], answer: "es", why: "A job is what someone is: ser." },
        { es: "Hoy ___ muy cansada.", en: "I am very tired today.", options: ["soy", "estoy"], answer: "estoy", why: "Tired is how you are right now: estar." },
        { es: "¿Dónde ___ el baño?", en: "Where is the toilet?", options: ["es", "está"], answer: "está", why: "Where something is takes estar." },
        { es: "Nosotros ___ de Inglaterra.", en: "We are from England.", options: ["somos", "estamos"], answer: "somos", why: "Where you are from is part of who you are: ser." },
        { es: "La sopa ___ fría.", en: "The soup is cold.", options: ["es", "está"], answer: "está", why: "The soup has gone cold; it is a state, so estar." },
        { es: "___ las tres de la tarde.", en: "It is three in the afternoon.", options: ["Son", "Están"], answer: "Son", why: "The time always takes ser." },
        { es: "Mi novia ___ muy inteligente.", en: "My girlfriend is very clever.", options: ["es", "está"], answer: "es", why: "A characteristic of a person: ser." },
        { es: "El museo ___ cerrado hoy.", en: "The museum is closed today.", options: ["es", "está"], answer: "está", why: "Closed is a state it is in today: estar." },
        { es: "Medellín ___ en Colombia.", en: "Medellín is in Colombia.", options: ["es", "está"], answer: "está", why: "Location takes estar, even for a city that will never move." },
        { es: "La mesa ___ de madera.", en: "The table is made of wood.", options: ["es", "está"], answer: "es", why: "What something is made of: ser." },
        { es: "Ya ___ listos, vámonos.", en: "We are ready now, let us go.", options: ["somos", "estamos"], answer: "estamos", why: "estar listo is to be ready. ser listo would mean to be clever." },
        { es: "La boda ___ en la iglesia del pueblo.", en: "The wedding is in the town church.", options: ["es", "está"], answer: "es", why: "An event taking place uses ser, even with a place: la fiesta es aquí." },
      ],
    },
    {
      id: "tener",
      title: "Tener, not to be",
      short: "tener",
      blurb: "Age, hunger, thirst, cold and fear are things you have, not things you are.",
      explain: [
        "Where English says I am, Spanish often says I have. You have years, hunger, thirst, heat, cold, fear, sleepiness, a hurry and being right.",
        "tengo veinticinco años, tengo hambre, tengo frío. Saying soy veinticinco or estoy hambre is the most common way English speakers give themselves away.",
        "Careful with heat. Tengo calor is I am hot. Estoy caliente means something else entirely, so do not say it about the weather.",
      ],
      examples: [
        ["Tengo veinticinco años.", "I am twenty-five."],
        ["¿Tienes hambre?", "Are you hungry?"],
        ["Tengo mucho calor.", "I am really hot."],
        ["Tienes razón.", "You are right."],
      ],
      mistake: ["Soy veinticinco años.", "Tengo veinticinco años.", "Age is had, not been."],
      items: [
        { es: "___ treinta años.", en: "I am thirty.", options: ["Soy", "Estoy", "Tengo"], answer: "Tengo", why: "Age is had: tengo treinta años." },
        { es: "¿___ hambre?", en: "Are you hungry?", options: ["Eres", "Estás", "Tienes"], answer: "Tienes", why: "Hunger is had: tener hambre." },
        { es: "Mi hermana ___ miedo de los perros.", en: "My sister is afraid of dogs.", options: ["es", "está", "tiene"], answer: "tiene", why: "Fear is had: tener miedo." },
        { es: "Abre la ventana, ___ mucho calor.", en: "Open the window, I am really hot.", options: ["estoy", "tengo", "soy"], answer: "tengo", why: "A person feeling hot: tener calor. Estoy caliente means something else." },
        { es: "En Bogotá siempre ___ frío por la noche.", en: "In Bogotá I am always cold at night.", options: ["estoy", "tengo", "soy"], answer: "tengo", why: "Feeling cold: tener frío." },
        { es: "Lo siento, ___ prisa.", en: "Sorry, I am in a hurry.", options: ["tengo", "estoy", "soy"], answer: "tengo", why: "Being in a hurry: tener prisa." },
        { es: "Tú ___ razón.", en: "You are right.", options: ["eres", "estás", "tienes"], answer: "tienes", why: "Being right: tener razón." },
        { es: "Los niños ___ sueño.", en: "The children are sleepy.", options: ["son", "están", "tienen"], answer: "tienen", why: "Being sleepy: tener sueño." },
        { es: "¿Cuántos años ___ tu abuela?", en: "How old is your grandmother?", options: ["es", "tiene", "está"], answer: "tiene", why: "Asking an age uses tener too." },
      ],
    },
    {
      id: "gender",
      title: "Gender and agreement",
      short: "gender",
      blurb: "Every noun is masculine or feminine, and the words around it have to match.",
      explain: [
        "Most nouns ending in o are masculine and most ending in a are feminine, but learn every noun with its article, el or la, as one unit.",
        "The famous exceptions: el día, el mapa, el problema, el idioma, el sofá are masculine; la mano, la radio, la foto, la moto are feminine.",
        "Articles and adjectives agree in gender and in number: el carro rojo, la casa roja, los carros rojos, las casas rojas. Adjectives ending in e or a consonant only change for the plural: el carro grande, la casa grande.",
        "A feminine noun starting with a stressed a takes el in the singular, just for the sound: el agua, el águila. It is still feminine: el agua está fría.",
      ],
      examples: [
        ["El problema es pequeño.", "The problem is small."],
        ["La mano me duele.", "My hand hurts."],
        ["Las casas son bonitas.", "The houses are pretty."],
        ["El agua está fría.", "The water is cold."],
      ],
      mistake: ["Una casa pequeño.", "Una casa pequeña.", "The adjective has to match the noun."],
      items: [
        { es: "___ problema es serio.", en: "The problem is serious.", options: ["El", "La"], answer: "El", why: "problema ends in a but is masculine: el problema." },
        { es: "Me duele ___ mano.", en: "My hand hurts.", options: ["el", "la"], answer: "la", why: "mano ends in o but is feminine: la mano." },
        { es: "Vivo en una casa muy ___.", en: "I live in a very small house.", options: ["pequeño", "pequeña"], answer: "pequeña", why: "casa is feminine, so the adjective is too." },
        { es: "Los zapatos son ___.", en: "The shoes are new.", options: ["nuevo", "nuevos", "nuevas"], answer: "nuevos", why: "zapatos is masculine plural: nuevos." },
        { es: "___ agua está fría.", en: "The water is cold.", options: ["El", "La"], answer: "El", why: "agua is feminine but starts with a stressed a, so it takes el in the singular. It is still fría, not frío." },
        { es: "Tengo dos ___ inglesas.", en: "I have two English friends.", options: ["amigos", "amigas"], answer: "amigas", why: "inglesas is feminine, so the friends are women: amigas." },
        { es: "___ día está bonito.", en: "It is a lovely day.", options: ["El", "La"], answer: "El", why: "día ends in a but is masculine: el día." },
        { es: "Las ventanas están ___.", en: "The windows are open.", options: ["abierto", "abiertas", "abiertos"], answer: "abiertas", why: "ventanas is feminine plural: abiertas." },
        { es: "Mi casa es ___.", en: "My house is big.", options: ["grande", "grandes"], answer: "grande", why: "Adjectives ending in e do not change for gender, only for number: la casa grande, las casas grandes." },
        { es: "¿Dónde está ___ foto?", en: "Where is the photo?", options: ["el", "la"], answer: "la", why: "foto is short for fotografía, so it is feminine: la foto." },
      ],
    },
    {
      id: "adjectives",
      title: "Where adjectives go",
      short: "adjectives",
      blurb: "After the noun, mostly. A red car is a car red.",
      explain: [
        "Describing adjectives normally come after the noun: un carro rojo, una casa grande, un hombre alto.",
        "Words of quantity come before: mucho, poco, otro, cada, primero and the numbers: muchos días, otra vez, tres cervezas.",
        "A few common adjectives can come before, and shorten when they do: bueno to buen, malo to mal, grande to gran. Un buen amigo is a good friend. Un gran amigo is a great friend; un amigo grande is a big one.",
      ],
      examples: [
        ["Tengo un carro rojo.", "I have a red car."],
        ["Es un buen restaurante.", "It is a good restaurant."],
        ["Necesito otra cerveza.", "I need another beer."],
      ],
      mistake: ["Un rojo carro.", "Un carro rojo.", "Colour goes after the noun."],
      items: [
        { es: "Compré ___.", en: "I bought a red shirt.", options: ["una camisa roja", "una roja camisa"], answer: "una camisa roja", why: "Colours go after the noun." },
        { es: "Es un ___ amigo.", en: "He is a good friend.", options: ["bueno", "buen"], answer: "buen", why: "bueno shortens to buen before a masculine noun." },
        { es: "Vivimos en ___.", en: "We live in a big city.", options: ["una ciudad grande", "una grande ciudad"], answer: "una ciudad grande", why: "Size after the noun means big. gran ciudad before it would mean great city." },
        { es: "Quiero ___, por favor.", en: "I would like another coffee, please.", options: ["otro café", "café otro", "un otro café"], answer: "otro café", why: "otro goes before the noun and never takes un: otro café." },
        { es: "Hace ___ tiempo.", en: "The weather is bad.", options: ["mal", "malo"], answer: "mal", why: "malo shortens to mal before a masculine noun." },
        { es: "Leí dos libros muy ___.", en: "I read two very interesting books.", options: ["interesante", "interesantes"], answer: "interesantes", why: "interesante does not change for gender, but it does for number: libros interesantes." },
        { es: "Hay ___ en la calle.", en: "There are lots of people in the street.", options: ["mucha gente", "gente mucha"], answer: "mucha gente", why: "Quantity words come before the noun." },
      ],
    },
    {
      id: "gustar",
      title: "Gustar and verbs like it",
      short: "gustar",
      blurb: "Me gusta means it pleases me. The thing you like is the subject.",
      explain: [
        "Spanish does not say I like the pizza. It says the pizza pleases me: me gusta la pizza. The thing liked is the subject, so the verb agrees with it.",
        "One thing liked, or an activity: me gusta. More than one thing: me gustan. Me gusta bailar; me gustan los perros.",
        "Who likes it goes before the verb as me, te, le, nos, les. To make it clear or to stress it, add a mí, a ti, a Ana: a Ana le gusta el café.",
        "encantar, interesar, importar, molestar, faltar and doler all work the same way: me encanta, me duele la cabeza, me duelen los pies.",
      ],
      examples: [
        ["Me gusta el café.", "I like coffee."],
        ["Me gustan los perros.", "I like dogs."],
        ["A mi mamá le encanta bailar.", "My mum loves dancing."],
        ["Me duelen los pies.", "My feet hurt."],
      ],
      mistake: ["Yo gusto la pizza.", "Me gusta la pizza.", "The pizza is the subject; you are the one it pleases."],
      items: [
        { es: "Me ___ el café colombiano.", en: "I like Colombian coffee.", options: ["gusta", "gustan", "gusto"], answer: "gusta", why: "One thing liked: gusta." },
        { es: "Me ___ las arepas.", en: "I like arepas.", options: ["gusta", "gustan"], answer: "gustan", why: "More than one thing liked: gustan." },
        { es: "¿Te ___ bailar?", en: "Do you like dancing?", options: ["gusta", "gustas", "gustan"], answer: "gusta", why: "An activity is singular: te gusta bailar." },
        { es: "A mi hermano ___ gusta el fútbol.", en: "My brother likes football.", options: ["le", "lo", "se"], answer: "le", why: "Someone else: le gusta. a mi hermano just makes clear who." },
        { es: "___ encanta esta canción.", en: "We love this song.", options: ["Nos", "Nosotros", "Les"], answer: "Nos", why: "We: nos encanta." },
        { es: "Me ___ los pies.", en: "My feet hurt.", options: ["duele", "duelen"], answer: "duelen", why: "doler works like gustar, and the feet are plural: me duelen." },
        { es: "A ellos no les ___ el ruido.", en: "They do not like noise.", options: ["gustan", "gusta", "gustamos"], answer: "gusta", why: "The thing liked is el ruido, singular: les gusta, whoever is doing the liking." },
        { es: "¿Te ___ si abro la ventana?", en: "Do you mind if I open the window?", options: ["molesta", "molestas"], answer: "molesta", why: "molestar works like gustar: does it bother you." },
        { es: "Me ___ dos dólares.", en: "I am two dollars short.", options: ["falta", "faltan"], answer: "faltan", why: "faltar works like gustar; dos dólares is plural." },
      ],
    },
    {
      id: "por-para",
      title: "Por and para",
      short: "por / para",
      blurb: "Both mean for, and they are not interchangeable.",
      explain: [
        "para looks ahead, to a goal: who something is for, where you are heading, what something is for, a deadline. Es para ti; salgo para Cali; estudio para aprender; para el lunes.",
        "por looks back, at a cause or a route: why something happened, what you paid or swapped, how long, the way through, and per. Gracias por todo; lo compré por diez mil; por dos horas; por el parque; dos veces por semana.",
        "A test that works most of the time: if you could say in order to or intended for, it is para. If you could say because of, in exchange for or through, it is por.",
      ],
      examples: [
        ["Este regalo es para ti.", "This present is for you."],
        ["Gracias por la ayuda.", "Thanks for the help."],
        ["Estudio español para viajar.", "I study Spanish in order to travel."],
        ["Caminamos por el centro.", "We walked through the centre."],
      ],
      mistake: ["Voy a tu casa por cenar.", "Voy a tu casa para cenar.", "In order to have dinner: a purpose, so para."],
      items: [
        { es: "Este regalo es ___ ti.", en: "This present is for you.", options: ["por", "para"], answer: "para", why: "Who something is intended for: para." },
        { es: "Gracias ___ todo.", en: "Thanks for everything.", options: ["por", "para"], answer: "por", why: "Thanks are for something that was done: por." },
        { es: "Estudio ___ ser ingeniero.", en: "I am studying to be an engineer.", options: ["por", "para"], answer: "para", why: "In order to: para." },
        { es: "Lo compré ___ veinte mil pesos.", en: "I bought it for twenty thousand pesos.", options: ["por", "para"], answer: "por", why: "In exchange for money: por." },
        { es: "Mañana salgo ___ Cartagena.", en: "Tomorrow I leave for Cartagena.", options: ["por", "para"], answer: "para", why: "A destination: para." },
        { es: "Caminamos ___ el parque.", en: "We walked through the park.", options: ["por", "para"], answer: "por", why: "Through or along a place: por." },
        { es: "Necesito el informe ___ el lunes.", en: "I need the report by Monday.", options: ["por", "para"], answer: "para", why: "A deadline: para." },
        { es: "Viví en Londres ___ dos años.", en: "I lived in London for two years.", options: ["por", "para"], answer: "por", why: "A length of time: por, or nothing at all." },
        { es: "Llegué tarde ___ el tráfico.", en: "I was late because of the traffic.", options: ["por", "para"], answer: "por", why: "Because of: por." },
        { es: "Voy al gimnasio tres veces ___ semana.", en: "I go to the gym three times a week.", options: ["por", "para"], answer: "por", why: "Per: por." },
        { es: "Este cuchillo es ___ cortar pan.", en: "This knife is for cutting bread.", options: ["por", "para"], answer: "para", why: "What something is used for: para." },
        { es: "Te llamo ___ teléfono.", en: "I will call you by phone.", options: ["por", "para"], answer: "por", why: "The means of doing something: por." },
      ],
    },
    {
      id: "personal-a",
      title: "The personal a",
      short: "personal a",
      blurb: "Put a before a person who is the object of the verb. English has nothing like it.",
      explain: [
        "When the thing a verb acts on is a specific person, Spanish puts a in front of them: veo a Ana, llamo a mi mamá, conozco a tu hermano.",
        "Not for things: veo la casa. And not after tener, even for people: tengo dos hermanos.",
        "Pets people are fond of often get it too: busco a mi perro.",
      ],
      examples: [
        ["Visité a mi abuela.", "I visited my grandmother."],
        ["¿Conoces a Juan?", "Do you know Juan?"],
        ["Veo la montaña.", "I can see the mountain."],
        ["Tengo dos hermanos.", "I have two brothers."],
      ],
      mistake: ["Visité mi abuela ayer.", "Visité a mi abuela ayer.", "Your grandmother is a person: a."],
      items: [
        { es: "Ayer visité ___ mi abuela.", en: "Yesterday I visited my grandmother.", options: ["a", "—"], answer: "a", why: "A specific person as the object: a." },
        { es: "Ayer visité ___ el museo.", en: "Yesterday I visited the museum.", options: ["a", "—"], answer: "—", why: "A museum is not a person: no a." },
        { es: "¿Conoces ___ mi hermano?", en: "Do you know my brother?", options: ["a", "—"], answer: "a", why: "Knowing a person: conocer a." },
        { es: "Tengo ___ tres primos.", en: "I have three cousins.", options: ["a", "—"], answer: "—", why: "tener never takes the personal a, even for people." },
        { es: "Voy a llamar ___ Ana.", en: "I am going to call Ana.", options: ["a", "—"], answer: "a", why: "Calling a person: a." },
        { es: "Busco ___ un taxi.", en: "I am looking for a taxi.", options: ["a", "—"], answer: "—", why: "A taxi is a thing: no a." },
        { es: "Espero ___ mi novia en la estación.", en: "I am waiting for my girlfriend at the station.", options: ["a", "—"], answer: "a", why: "Waiting for a person: esperar a." },
        { es: "Veo ___ las montañas desde aquí.", en: "I can see the mountains from here.", options: ["a", "—"], answer: "—", why: "Mountains are things: no a." },
      ],
    },
    {
      id: "hay-esta",
      title: "Hay or está",
      short: "hay / está",
      blurb: "Whether something exists, or where a particular one is.",
      explain: [
        "hay is there is or there are. It says something exists, and it never changes: hay un banco, hay dos bancos. It goes with un, una, numbers, mucho or no article at all.",
        "está and están say where a particular thing is: el banco está en la esquina. They go with el, la, mi, tu and names.",
        "So: ¿hay un banco por aquí? asks whether there is one. ¿Dónde está el banco? asks where the one you have in mind is.",
      ],
      examples: [
        ["Hay un supermercado cerca.", "There is a supermarket nearby."],
        ["El supermercado está en la esquina.", "The supermarket is on the corner."],
        ["Hay muchos turistas hoy.", "There are a lot of tourists today."],
      ],
      mistake: ["Hay el banco en la esquina.", "El banco está en la esquina.", "A particular bank: está."],
      items: [
        { es: "¿___ un cajero por aquí?", en: "Is there a cash machine around here?", options: ["Hay", "Está"], answer: "Hay", why: "Asking whether one exists, with un: hay." },
        { es: "¿Dónde ___ mi celular?", en: "Where is my phone?", options: ["hay", "está"], answer: "está", why: "Where a particular thing is: está." },
        { es: "___ muchos turistas en diciembre.", en: "There are lots of tourists in December.", options: ["Hay", "Están"], answer: "Hay", why: "There are, saying they exist: hay, which never goes plural." },
        { es: "Los niños ___ en el parque.", en: "The children are in the park.", options: ["hay", "están"], answer: "están", why: "Where particular people are: están." },
        { es: "En la nevera ___ dos cervezas.", en: "There are two beers in the fridge.", options: ["hay", "están"], answer: "hay", why: "With a number, saying they exist: hay." },
        { es: "La farmacia ___ al lado del banco.", en: "The chemist's is next to the bank.", options: ["hay", "está"], answer: "está", why: "la farmacia is a particular one: está." },
        { es: "No ___ agua caliente.", en: "There is no hot water.", options: ["hay", "está"], answer: "hay", why: "Whether something exists, no article: hay." },
      ],
    },
    {
      id: "little-words",
      title: "Al, del, muy and mucho",
      short: "al, del, muy",
      blurb: "Four little words that English speakers get wrong all day.",
      explain: [
        "a and el always run together into al, and de and el into del: voy al cine, vengo del trabajo. Never a el or de el. Only el does this; a la and de la stay apart.",
        "muy is very and goes before adjectives and adverbs: muy bueno, muy bien, muy tarde. It never stands on its own.",
        "mucho is a lot or much. On its own or after a verb it does not change: te quiero mucho. Before a noun it agrees: mucha gente, muchos días, muchas gracias.",
      ],
      examples: [
        ["Voy al supermercado.", "I am going to the supermarket."],
        ["Vengo del aeropuerto.", "I am coming from the airport."],
        ["Es muy caro.", "It is very expensive."],
        ["Trabajo mucho.", "I work a lot."],
      ],
      mistake: ["Voy a el cine.", "Voy al cine.", "a and el always become al."],
      items: [
        { es: "Mañana vamos ___ cine.", en: "Tomorrow we are going to the cinema.", options: ["a el", "al", "a la"], answer: "al", why: "a and el always run together: al." },
        { es: "Vengo ___ trabajo.", en: "I am coming from work.", options: ["de el", "del", "de la"], answer: "del", why: "de and el always run together: del." },
        { es: "Vamos ___ playa.", en: "Let us go to the beach.", options: ["al", "a la"], answer: "a la", why: "playa is feminine; only el contracts, so a la stays apart." },
        { es: "La comida está ___ rica.", en: "The food is really tasty.", options: ["muy", "mucho", "mucha"], answer: "muy", why: "Before an adjective: muy." },
        { es: "Te quiero ___.", en: "I love you a lot.", options: ["muy", "mucho"], answer: "mucho", why: "After a verb, a lot: mucho, and it does not change." },
        { es: "Hay ___ gente aquí.", en: "There are a lot of people here.", options: ["muy", "mucho", "mucha"], answer: "mucha", why: "Before a noun mucho agrees: gente is feminine, so mucha." },
        { es: "¡___ gracias!", en: "Thank you very much!", options: ["Muy", "Muchas", "Mucho"], answer: "Muchas", why: "gracias is a feminine plural noun: muchas gracias. Muy gracias is a classic mistake." },
        { es: "Llegamos ___ tarde.", en: "We arrived very late.", options: ["muy", "mucho"], answer: "muy", why: "Before an adverb: muy." },
      ],
    },
    {
      id: "ir-a",
      title: "Going to: ir a",
      short: "ir a",
      blurb: "The future people actually use: voy a comer, vamos a ver.",
      explain: [
        "To talk about plans, Spanish mostly uses ir a and the infinitive, just like going to: voy a comer, vamos a salir, va a llover.",
        "ir is irregular: voy, vas, va, vamos, van. The a is always there, and the next verb never changes: voy a ir, not voy ir.",
        "Vamos a on its own is also let us: vamos a ver, let us see.",
      ],
      examples: [
        ["Voy a llamar a mi mamá.", "I am going to call my mum."],
        ["Va a llover.", "It is going to rain."],
        ["¿Qué vas a hacer el sábado?", "What are you going to do on Saturday?"],
      ],
      mistake: ["Voy comer.", "Voy a comer.", "The a is never left out."],
      items: [
        { es: "Mañana ___ a viajar a Cali.", en: "Tomorrow I am going to travel to Cali.", options: ["voy", "vas", "va"], answer: "voy", why: "I: voy a." },
        { es: "¿Qué ___ a hacer hoy?", en: "What are you going to do today?", options: ["voy", "vas", "vamos"], answer: "vas", why: "You: vas a." },
        { es: "Creo que ___ a llover.", en: "I think it is going to rain.", options: ["va", "van", "vas"], answer: "va", why: "It: va a llover." },
        { es: "Nosotros ___ a cenar en casa.", en: "We are going to have dinner at home.", options: ["vamos", "van", "va"], answer: "vamos", why: "We: vamos a." },
        { es: "Voy ___ comprar pan.", en: "I am going to buy bread.", options: ["a", "—", "de"], answer: "a", why: "ir a and the infinitive: the a is always there." },
        { es: "Mis padres ___ a visitarme en diciembre.", en: "My parents are going to visit me in December.", options: ["va", "van", "vamos"], answer: "van", why: "They: van a." },
      ],
    },
    {
      id: "past-tenses",
      title: "The two past tenses",
      short: "past tenses",
      blurb: "What happened, and what was going on: the preterite and the imperfect.",
      explain: [
        "The preterite is for something that happened and finished: a single event, a fixed number of times, a stretch with a clear end. Ayer fui al cine. Viví allí dos años.",
        "The imperfect is for the background: what used to happen, what was going on, how things were, the time and people's ages in the past. Cuando era niño, jugaba fútbol. Hacía calor.",
        "Together they tell a story: the imperfect sets the scene, the preterite moves it on. Estaba en la ducha cuando sonó el teléfono: I was in the shower (background) when the phone rang (event).",
        "Words that push towards the preterite: ayer, anoche, una vez, el año pasado. Words that push towards the imperfect: siempre, todos los días, de niño, mientras.",
      ],
      examples: [
        ["Ayer comí arepas.", "Yesterday I ate arepas."],
        ["De niño comía arepas todos los días.", "As a child I ate arepas every day."],
        ["Estaba en la ducha cuando llamaste.", "I was in the shower when you called."],
        ["Eran las diez cuando llegamos.", "It was ten o'clock when we arrived."],
      ],
      mistake: ["Cuando fui niño, jugué en el parque.", "Cuando era niño, jugaba en el parque.", "Childhood and habits are background: imperfect."],
      items: [
        { es: "Ayer ___ al cine.", en: "Yesterday I went to the cinema.", options: ["fui", "iba"], answer: "fui", why: "One finished event, yesterday: preterite." },
        { es: "De niño ___ al parque todos los domingos.", en: "As a child I used to go to the park every Sunday.", options: ["fui", "iba"], answer: "iba", why: "A habit in the past, todos los domingos: imperfect." },
        { es: "Cuando ___ niño, vivía en Londres.", en: "When I was a child, I lived in London.", options: ["fui", "era"], answer: "era", why: "Age and childhood are background: imperfect." },
        { es: "___ las nueve cuando llegué.", en: "It was nine o'clock when I arrived.", options: ["Fueron", "Eran"], answer: "Eran", why: "The time in the past is always imperfect." },
        { es: "Estaba en la ducha cuando ___ el teléfono.", en: "I was in the shower when the phone rang.", options: ["sonó", "sonaba"], answer: "sonó", why: "The event that interrupts the scene: preterite." },
        { es: "___ mucho calor esa noche.", en: "It was very hot that night.", options: ["Hizo", "Hacía"], answer: "Hacía", why: "Weather as the setting of a scene: imperfect." },
        { es: "Anoche ___ una película muy buena.", en: "Last night I watched a very good film.", options: ["vi", "veía"], answer: "vi", why: "Anoche, a finished event: preterite." },
        { es: "Mientras yo cocinaba, mi novia ___ música.", en: "While I was cooking, my girlfriend was listening to music.", options: ["escuchó", "escuchaba"], answer: "escuchaba", why: "Two things going on at once, mientras: imperfect." },
        { es: "Viví en Londres dos años y luego ___ a Colombia.", en: "I lived in London for two years and then went back to Colombia.", options: ["volví", "volvía"], answer: "volví", why: "A sequence of finished events: preterite." },
        { es: "Mi abuelo siempre me ___ historias.", en: "My grandfather always used to tell me stories.", options: ["contó", "contaba"], answer: "contaba", why: "siempre, a repeated habit: imperfect." },
        { es: "El año pasado ___ a Colombia por primera vez.", en: "Last year I went to Colombia for the first time.", options: ["fui", "iba"], answer: "fui", why: "A single trip, por primera vez: preterite." },
      ],
    },
    {
      id: "pronouns",
      title: "Lo, la, le and se",
      short: "lo, la, le",
      blurb: "Object pronouns: it, him, her, to him, to her, and where they go.",
      explain: [
        "The thing or person a verb acts on, the direct object, is lo for masculine and la for feminine: ¿el libro? Lo tengo. ¿La llave? La tengo.",
        "The person something is given or said to, the indirect object, is le, or les for more than one: le di el dinero, I gave him the money.",
        "They go before a conjugated verb: lo veo. With an infinitive or a gerund they can also go on the end: voy a verlo, or lo voy a ver.",
        "When le and lo meet, le turns into se, because le lo is never said: se lo di, I gave it to him.",
      ],
      examples: [
        ["¿Tienes las llaves? Sí, las tengo.", "Have you got the keys? Yes, I have got them."],
        ["Le mandé un mensaje a Ana.", "I sent Ana a message."],
        ["Se lo expliqué ayer.", "I explained it to him yesterday."],
        ["Voy a comprarlo.", "I am going to buy it."],
      ],
      mistake: ["Le lo di.", "Se lo di.", "le becomes se before lo, la, los or las."],
      items: [
        { es: "¿El pasaporte? Sí, ___ tengo.", en: "The passport? Yes, I have got it.", options: ["lo", "la", "le"], answer: "lo", why: "el pasaporte is masculine and the direct object: lo." },
        { es: "¿La cuenta? ___ pagué yo.", en: "The bill? I paid it.", options: ["Lo", "La", "Le"], answer: "La", why: "la cuenta is feminine and the direct object: la." },
        { es: "___ di el regalo a mi mamá.", en: "I gave my mum the present.", options: ["Le", "La", "Lo"], answer: "Le", why: "Given to someone, the indirect object: le." },
        { es: "¿El regalo? Ya ___ lo di.", en: "The present? I have already given it to her.", options: ["le", "se", "la"], answer: "se", why: "le becomes se before lo: se lo di." },
        { es: "¿Las maletas? No ___ encuentro.", en: "The suitcases? I cannot find them.", options: ["los", "las", "les"], answer: "las", why: "las maletas, feminine plural: las." },
        { es: "Voy a ___ mañana.", en: "I am going to call her tomorrow.", options: ["llamarla", "llamarle", "la llamar"], answer: "llamarla", why: "With an infinitive the pronoun can go on the end: llamarla. Or la voy a llamar." },
        { es: "A mis padres ___ escribo cada semana.", en: "I write to my parents every week.", options: ["los", "les", "le"], answer: "les", why: "Written to more than one person: les." },
        { es: "¿Me pasas la sal? Sí, ya ___ paso.", en: "Will you pass me the salt? Yes, I am passing it to you.", options: ["te la", "la te", "te lo"], answer: "te la", why: "Indirect before direct: te la, and sal is feminine." },
      ],
    },
    {
      id: "reflexive",
      title: "Me, te, se: verbs about yourself",
      short: "reflexive",
      blurb: "Getting up, getting dressed, being called: the verbs that take se.",
      explain: [
        "Many everyday verbs are done to yourself, and carry a pronoun that matches the subject: me levanto, te levantas, se levanta, nos levantamos, se levantan.",
        "Your daily routine is full of them: despertarse, levantarse, ducharse, vestirse, acostarse. So is your name: me llamo, literally I call myself.",
        "With body parts and clothes, Spanish uses the article, not my: me lavo las manos, me pongo la chaqueta.",
        "Some change meaning with se: ir is to go, irse is to leave; dormir is to sleep, dormirse is to fall asleep.",
      ],
      examples: [
        ["Me levanto a las seis.", "I get up at six."],
        ["¿Cómo te llamas?", "What is your name?"],
        ["Me lavo las manos.", "I wash my hands."],
        ["Ya me voy.", "I am off now."],
      ],
      mistake: ["Levanto a las seis.", "Me levanto a las seis.", "Without me it means I lift something at six."],
      items: [
        { es: "___ levanto a las seis.", en: "I get up at six.", options: ["Me", "Te", "Se"], answer: "Me", why: "I: me levanto." },
        { es: "¿A qué hora ___ acuestas?", en: "What time do you go to bed?", options: ["me", "te", "se"], answer: "te", why: "You: te acuestas." },
        { es: "Mi hermano ___ llama Daniel.", en: "My brother is called Daniel.", options: ["me", "se", "le"], answer: "se", why: "He: se llama." },
        { es: "Nosotros ___ duchamos por la mañana.", en: "We have a shower in the morning.", options: ["nos", "se", "os"], answer: "nos", why: "We: nos duchamos. os is the Spain-only vosotros form." },
        { es: "Me lavo ___ manos.", en: "I wash my hands.", options: ["mis", "las"], answer: "las", why: "With body parts Spanish uses the article: me lavo las manos." },
        { es: "Ya es tarde, ___ voy.", en: "It is late, I am off.", options: ["me", "—"], answer: "me", why: "irse is to leave: me voy. Voy on its own needs somewhere to go." },
      ],
    },
    {
      id: "subjunctive",
      title: "Wishes and doubts: the subjunctive",
      short: "subjunctive",
      blurb: "Espero que vengas: the verb changes after wanting, hoping and doubting.",
      explain: [
        "After que, when the first part expresses a wish, a hope, a feeling, a request or a doubt about someone else's action, the second verb goes into the subjunctive. Espero que vengas; quiero que me llames; no creo que sea verdad.",
        "The present subjunctive swaps the vowel: ar verbs take e (hable, hables), er and ir verbs take a (coma, viva). Irregulars use the yo form's stem: tengo gives tenga, hago gives haga, vengo gives venga.",
        "Ojalá always takes it: ojalá llueva. So does cuando about the future: cuando llegues, llámame.",
        "When nothing is wished or doubted, it is the ordinary indicative: creo que es verdad, sé que viene.",
      ],
      examples: [
        ["Espero que estés bien.", "I hope you are well."],
        ["Quiero que vengas.", "I want you to come."],
        ["Ojalá no llueva mañana.", "I hope it does not rain tomorrow."],
        ["Cuando llegues, llámame.", "When you arrive, call me."],
      ],
      mistake: ["Espero que vienes.", "Espero que vengas.", "Hoping takes the subjunctive."],
      items: [
        { es: "Espero que ___ bien.", en: "I hope you are well.", options: ["estás", "estés"], answer: "estés", why: "After espero que: subjunctive." },
        { es: "Quiero que ___ a la fiesta.", en: "I want you to come to the party.", options: ["vienes", "vengas"], answer: "vengas", why: "Wanting someone else to do something: subjunctive." },
        { es: "Ojalá no ___ mañana.", en: "I hope it does not rain tomorrow.", options: ["llueve", "llueva"], answer: "llueva", why: "ojalá always takes the subjunctive." },
        { es: "Cuando ___ a Bogotá, llámame.", en: "When you get to Bogotá, call me.", options: ["llegas", "llegues"], answer: "llegues", why: "cuando about something still to happen: subjunctive." },
        { es: "Creo que ___ verdad.", en: "I think it is true.", options: ["es", "sea"], answer: "es", why: "Believing something is true is not a doubt: indicative." },
        { es: "No creo que ___ verdad.", en: "I do not think it is true.", options: ["es", "sea"], answer: "sea", why: "Doubting it: subjunctive." },
        { es: "Mi mamá quiere que yo ___ más.", en: "My mum wants me to eat more.", options: ["como", "coma"], answer: "coma", why: "Someone wanting someone else to act: subjunctive. er verbs take a." },
        { es: "Es importante que ___ temprano.", en: "It is important that you arrive early.", options: ["llegas", "llegues"], answer: "llegues", why: "Es importante que: subjunctive." },
      ],
    },
    {
      id: "false-friends",
      title: "False friends",
      short: "false friends",
      blurb: "Words that look English and mean something else.",
      explain: [
        "Spanish and English share thousands of words, which is a gift until one of them betrays you. These are the ones that cause real embarrassment or real confusion.",
        "embarazada is pregnant, not embarrassed: that is avergonzado, or in Colombia, qué pena. éxito is success, not exit: that is salida. librería is a bookshop; a library is a biblioteca.",
        "actualmente is currently, not actually: that is en realidad. recordar is to remember; to record is grabar. molestar is to bother. sensible is sensitive; sensible is sensato.",
      ],
      examples: [
        ["Estoy embarazada.", "I am pregnant."],
        ["¡Qué pena!", "How embarrassing!"],
        ["¿Dónde está la salida?", "Where is the exit?"],
        ["Actualmente vivo en Medellín.", "I currently live in Medellín."],
      ],
      mistake: ["Estoy embarazado por el error.", "Estoy avergonzado por el error.", "embarazada is pregnant."],
      items: [
        { es: "Estoy muy ___, me equivoqué de nombre.", en: "I am very embarrassed, I got the name wrong.", options: ["embarazado", "avergonzado"], answer: "avergonzado", why: "embarazada is pregnant. Embarrassed is avergonzado." },
        { es: "¿Dónde está la ___?", en: "Where is the exit?", options: ["éxito", "salida"], answer: "salida", why: "éxito is success. The way out is la salida." },
        { es: "Compré el libro en una ___.", en: "I bought the book in a bookshop.", options: ["librería", "biblioteca"], answer: "librería", why: "A librería sells books; a biblioteca lends them." },
        { es: "___ trabajo en una empresa de energía.", en: "I currently work for an energy company.", options: ["Actualmente", "En realidad"], answer: "Actualmente", why: "actualmente is currently. Actually is en realidad." },
        { es: "No ___ su nombre.", en: "I do not remember his name.", options: ["recuerdo", "grabo"], answer: "recuerdo", why: "recordar is to remember. To record is grabar." },
        { es: "La película fue un gran ___.", en: "The film was a great success.", options: ["éxito", "suceso"], answer: "éxito", why: "éxito is success. suceso is an event, often a bad one." },
        { es: "Abre la ventana, ___.", en: "Open the window, I am hot.", options: ["estoy caliente", "tengo calor"], answer: "tengo calor", why: "A person feeling hot: tengo calor. Estoy caliente means something else entirely." },
        { es: "Mi hermana es muy ___, llora con todas las películas.", en: "My sister is very sensitive, she cries at every film.", options: ["sensible", "sensata"], answer: "sensible", why: "sensible is sensitive. Sensible in the English sense is sensata." },
      ],
    },
  ],
};
