/* Seed bank: the supplied vocabulary and sentence data, verbatim.

   This is a .js file rather than two .json files for one reason: the app
   has to open by double-clicking index.html, and a page on file:// is not
   allowed to fetch a sibling .json. The content is unchanged; only the
   assignment on the front is new, so it stays hand-editable and diffable
   exactly as JSON would be.

   This is the single source of truth for the bank. Words and sentences
   added through the Manage screen live in localStorage on top of it, and
   come out in an Export, so nothing added by hand here is ever lost.

   vocabulary: { id, es, es_alt[], en[], pos, note }
   sentences:  { id, wordId, es, answer, en }   target wrapped in {braces}
*/
const SEED = {
  meta: {"vocabulary": {"name": "Idioma vocabulary seed", "dialect": "Latin American, Colombian-leaning", "notes": "en[] holds all accepted English answers (for Spanish to English). es plus es_alt[] hold all accepted Spanish answers (for English to Spanish). note is shown on reveal.", "corrections_applied": ["near = cerca (was 'circa')", "to wait = esperar (was 'entender')", "good luck = buena suerte (was 'buenas suertes')", "pleasure = placer (was 'prazer', which is Portuguese)", "spelling: tarjeta, efectivo, bano to baño", "mejor = better (the best = el/la mejor); peor = worse (the worst = el/la peor)", "'puesta = preservation' dropped: the gloss was wrong and the intended word was unclear"]}, "sentences": {"name": "Idioma sentence seed", "dialect": "Latin American, Colombian-leaning", "format": "es holds the full sentence with the target surface form wrapped in {curly braces}. answer is the exact string to type. wordId links to a vocabulary word. Conjugated/inflected forms are intentional: the learner types the form shown, not the dictionary form.", "usage": "Used at mastery levels 8-10 as fill-in-the-blank. Accent- and case-insensitive matching; the accented answer is still displayed on reveal."}},
  vocabulary: [
    {"id": "habitacion", "es": "habitación", "es_alt": ["cuarto"], "en": ["room"], "pos": "noun", "note": "f. In Colombia 'cuarto' is very common for room/bedroom."},
    {"id": "dormitorio", "es": "dormitorio", "es_alt": ["cuarto"], "en": ["bedroom"], "pos": "noun", "note": "m."},
    {"id": "bano", "es": "baño", "en": ["bathroom", "toilet"], "pos": "noun", "note": "m."},
    {"id": "cama", "es": "cama", "en": ["bed"], "pos": "noun", "note": "f."},
    {"id": "comida", "es": "comida", "en": ["food", "meal"], "pos": "noun", "note": "f."},
    {"id": "agua", "es": "agua", "en": ["water"], "pos": "noun", "note": "f. but takes 'el agua' in singular."},
    {"id": "caneca", "es": "caneca", "en": ["bin", "trash can"], "pos": "noun", "note": "Colombian. Spain uses papelera / cubo de basura."},
    {"id": "bolsa", "es": "bolsa", "en": ["bag"], "pos": "noun", "note": "f. Plural bolsas."},
    {"id": "calle", "es": "calle", "en": ["street"], "pos": "noun", "note": "f."},
    {"id": "mesa", "es": "mesa", "en": ["table"], "pos": "noun", "note": "f."},
    {"id": "plato", "es": "plato", "en": ["plate", "dish"], "pos": "noun", "note": "m."},
    {"id": "vaso-de-agua", "es": "vaso de agua", "en": ["glass of water"], "pos": "phrase", "note": "'vaso' = glass (water); 'copa' = stemmed glass (wine)."},
    {"id": "copa-vino", "es": "copa de vino", "en": ["glass of wine"], "pos": "phrase", "note": "vino blanco = white, vino tinto = red."},
    {"id": "tinto", "es": "tinto", "en": ["black coffee"], "pos": "noun", "note": "COLOMBIA GOTCHA: 'un tinto' = a small black coffee. Red wine is 'vino tinto'."},
    {"id": "tocineta", "es": "tocineta", "en": ["bacon"], "pos": "noun", "note": "Colombian. Spain uses beicon / panceta."},
    {"id": "cambio", "es": "cambio", "en": ["change"], "pos": "noun", "note": "m. change (money) or a change generally."},
    {"id": "punto", "es": "punto", "en": ["point"], "pos": "noun", "note": "m."},
    {"id": "pinta", "es": "pinta", "en": ["pint"], "pos": "noun", "note": "f. Rare in Colombia; you'd usually just order 'una cerveza'."},
    {"id": "vez", "es": "vez", "en": ["time", "occasion"], "pos": "noun", "note": "f. As in 'una vez' = once, 'la primera vez' = the first time."},
    {"id": "camino", "es": "camino", "en": ["way", "path", "road"], "pos": "noun", "note": "m."},
    {"id": "nuestro", "es": "nuestro", "es_alt": ["nuestra"], "en": ["our"], "pos": "determiner", "note": "Agrees: nuestro/nuestra/nuestros/nuestras."},
    {"id": "mi", "es": "mi", "en": ["my"], "pos": "determiner", "note": ""},
    {"id": "tu", "es": "tu", "en": ["your"], "pos": "determiner", "note": "'tu' (your) has no accent; 'tú' (you) does."},
    {"id": "nosotros", "es": "nosotros", "en": ["us", "we"], "pos": "pronoun", "note": ""},
    {"id": "abierto", "es": "abierto", "es_alt": ["abierta"], "en": ["open"], "pos": "adjective", "note": "Agrees for gender."},
    {"id": "cerrado", "es": "cerrado", "es_alt": ["cerrada"], "en": ["closed", "shut"], "pos": "adjective", "note": "Agrees for gender."},
    {"id": "cansado", "es": "cansado", "es_alt": ["cansada"], "en": ["tired"], "pos": "adjective", "note": "Use with estar."},
    {"id": "feliz", "es": "feliz", "en": ["happy"], "pos": "adjective", "note": "Also 'contento/a'."},
    {"id": "triste", "es": "triste", "en": ["sad"], "pos": "adjective", "note": ""},
    {"id": "fuerte", "es": "fuerte", "en": ["strong"], "pos": "adjective", "note": ""},
    {"id": "debil", "es": "débil", "en": ["weak"], "pos": "adjective", "note": ""},
    {"id": "mismo", "es": "mismo", "es_alt": ["misma"], "en": ["same"], "pos": "adjective", "note": "'el mismo' = the same one."},
    {"id": "diferente", "es": "diferente", "en": ["different"], "pos": "adjective", "note": ""},
    {"id": "mejor", "es": "mejor", "en": ["better"], "pos": "adjective", "note": "'the best' = el/la mejor."},
    {"id": "peor", "es": "peor", "en": ["worse"], "pos": "adjective", "note": "'the worst' = el/la peor."},
    {"id": "listo", "es": "listo", "es_alt": ["lista"], "en": ["ready"], "pos": "adjective", "note": "'estar listo' = ready; 'ser listo' = clever."},
    {"id": "pleno", "es": "pleno", "es_alt": ["plena"], "en": ["full", "complete"], "pos": "adjective", "note": "Sense of 'in the middle of / peak' (en plena calle). A full container = lleno/llena."},
    {"id": "lleno", "es": "lleno", "es_alt": ["llena"], "en": ["full"], "pos": "adjective", "note": "For containers, seats, etc. (el vaso está lleno)."},
    {"id": "casi", "es": "casi", "en": ["almost", "nearly"], "pos": "adverb", "note": ""},
    {"id": "arriba", "es": "arriba", "en": ["up", "upstairs", "above"], "pos": "adverb", "note": ""},
    {"id": "abajo", "es": "abajo", "en": ["down", "downstairs", "below"], "pos": "adverb", "note": ""},
    {"id": "alli", "es": "allí", "es_alt": ["allá"], "en": ["there"], "pos": "adverb", "note": "Colombia often uses 'allá'."},
    {"id": "aqui", "es": "aquí", "es_alt": ["acá"], "en": ["here"], "pos": "adverb", "note": "Colombia often uses 'acá'."},
    {"id": "afuera", "es": "afuera", "es_alt": ["fuera"], "en": ["outside"], "pos": "adverb", "note": ""},
    {"id": "adentro", "es": "adentro", "es_alt": ["dentro"], "en": ["inside"], "pos": "adverb", "note": ""},
    {"id": "izquierda", "es": "izquierda", "en": ["left"], "pos": "noun", "note": "a la izquierda = on/to the left."},
    {"id": "derecha", "es": "derecha", "en": ["right"], "pos": "noun", "note": "a la derecha = on/to the right."},
    {"id": "enfrente", "es": "enfrente", "es_alt": ["enfrente de", "delante de"], "en": ["in front of", "opposite"], "pos": "adverb", "note": ""},
    {"id": "cerca", "es": "cerca", "en": ["near", "close"], "pos": "adverb", "note": "cerca de = near to."},
    {"id": "lejos", "es": "lejos", "en": ["far"], "pos": "adverb", "note": "lejos de = far from."},
    {"id": "lunes", "es": "lunes", "en": ["monday"], "pos": "days", "note": "Days are lowercase in Spanish."},
    {"id": "martes", "es": "martes", "en": ["tuesday"], "pos": "days", "note": ""},
    {"id": "miercoles", "es": "miércoles", "en": ["wednesday"], "pos": "days", "note": ""},
    {"id": "jueves", "es": "jueves", "en": ["thursday"], "pos": "days", "note": ""},
    {"id": "viernes", "es": "viernes", "en": ["friday"], "pos": "days", "note": ""},
    {"id": "sabado", "es": "sábado", "en": ["saturday"], "pos": "days", "note": ""},
    {"id": "domingo", "es": "domingo", "en": ["sunday"], "pos": "days", "note": ""},
    {"id": "quien", "es": "¿quién?", "en": ["who"], "pos": "question", "note": ""},
    {"id": "que", "es": "¿qué?", "en": ["what"], "pos": "question", "note": ""},
    {"id": "donde", "es": "¿dónde?", "en": ["where"], "pos": "question", "note": ""},
    {"id": "cuando", "es": "¿cuándo?", "en": ["when"], "pos": "question", "note": "Question 'cuándo' has an accent; conjunction 'cuando' does not."},
    {"id": "a-que-hora", "es": "¿a qué hora?", "en": ["what time"], "pos": "question", "note": ""},
    {"id": "por-que", "es": "¿por qué?", "en": ["why"], "pos": "question", "note": "Two words for the question; 'porque' (one word) = because."},
    {"id": "como", "es": "¿cómo?", "en": ["how"], "pos": "question", "note": ""},
    {"id": "cuanto", "es": "¿cuánto?", "en": ["how much"], "pos": "question", "note": ""},
    {"id": "cuantos", "es": "¿cuántos?", "es_alt": ["¿cuántas?"], "en": ["how many"], "pos": "question", "note": "Agrees: cuántos/cuántas."},
    {"id": "cada-cuanto", "es": "¿cada cuánto?", "en": ["how often"], "pos": "question", "note": ""},
    {"id": "por-cuanto-tiempo", "es": "¿por cuánto tiempo?", "en": ["how long"], "pos": "question", "note": "Duration. 'how long' (length) = qué tan largo."},
    {"id": "alguna", "es": "alguna", "es_alt": ["alguno", "algunas", "algunos"], "en": ["some", "any"], "pos": "determiner", "note": "Agrees for gender and number."},
    {"id": "asimismo", "es": "asimismo", "en": ["furthermore", "likewise", "also"], "pos": "adverb", "note": "Formal. 'además' / 'también' are more common in speech."},
    {"id": "entonces", "es": "entonces", "en": ["therefore", "so", "then"], "pos": "adverb", "note": ""},
    {"id": "esto", "es": "esto", "es_alt": ["este", "esta"], "en": ["this"], "pos": "pronoun", "note": "esto is neuter; este/esta agree with a noun."},
    {"id": "eso", "es": "eso", "es_alt": ["ese", "esa"], "en": ["that"], "pos": "pronoun", "note": "eso is neuter; ese/esa agree with a noun."},
    {"id": "desde", "es": "desde", "en": ["from", "since"], "pos": "preposition", "note": ""},
    {"id": "para", "es": "para", "en": ["for", "in order to", "to"], "pos": "preposition", "note": "Purpose, goal, destination, deadline. 'para ti' = for you."},
    {"id": "por", "es": "por", "en": ["for", "by", "through", "because of"], "pos": "preposition", "note": "Cause, exchange, movement through. 'gracias por' = thanks for."},
    {"id": "cuanto-cuesta", "es": "¿cuánto cuesta?", "en": ["how much is it", "how much does it cost"], "pos": "phrase", "note": ""},
    {"id": "hay-un", "es": "hay un", "es_alt": ["hay una"], "en": ["is there a", "there is a"], "pos": "phrase", "note": "'hay' = there is / there are."},
    {"id": "algo-mas", "es": "¿algo más?", "en": ["anything else"], "pos": "phrase", "note": ""},
    {"id": "cuanto-tiempo", "es": "¿cuánto tiempo?", "en": ["how long"], "pos": "phrase", "note": ""},
    {"id": "hasta-luego", "es": "hasta luego", "es_alt": ["nos vemos"], "en": ["see you later"], "pos": "phrase", "note": ""},
    {"id": "buena-suerte", "es": "buena suerte", "en": ["good luck"], "pos": "phrase", "note": "Singular."},
    {"id": "de-nada", "es": "de nada", "en": ["you're welcome"], "pos": "phrase", "note": ""},
    {"id": "placer", "es": "placer", "es_alt": ["mucho gusto"], "en": ["pleasure"], "pos": "noun", "note": "'un placer' / 'mucho gusto' = pleasure to meet you."},
    {"id": "dime", "es": "dime", "en": ["tell me"], "pos": "phrase", "note": "Imperative of decir + me."},
    {"id": "por-supuesto", "es": "por supuesto", "es_alt": ["claro"], "en": ["of course"], "pos": "phrase", "note": "'claro' is the everyday Colombian version."},
    {"id": "que-quieres", "es": "¿qué quieres?", "en": ["what do you want"], "pos": "phrase", "note": "Neutral. '¿qué pretendes?' exists but is pointed/confrontational, closer to 'what are you after?'."},
    {"id": "llamando", "es": "llamando", "en": ["calling"], "pos": "verb", "note": "Gerund of llamar (to call)."},
    {"id": "siguiente-en-la-fila", "es": "siguiente en la fila", "en": ["next in the queue", "next in line"], "pos": "phrase", "note": "'fila' = queue/line in Colombia."},
    {"id": "salida", "es": "salida", "en": ["exit", "checkout", "departure"], "pos": "noun", "note": "f. '¿a qué hora es la salida?' = what time is checkout?"},
    {"id": "con-tarjeta", "es": "con tarjeta", "en": ["by card", "with card"], "pos": "phrase", "note": ""},
    {"id": "en-efectivo", "es": "en efectivo", "en": ["by cash", "in cash"], "pos": "phrase", "note": ""},
    {"id": "pedir", "es": "pedir", "en": ["to order", "to ask for"], "pos": "verb", "note": "Stem change e to i."},
    {"id": "poder", "es": "poder", "en": ["to be able to", "can"], "pos": "verb", "note": "Stem change o to ue (puedo)."},
    {"id": "viajar", "es": "viajar", "en": ["to travel"], "pos": "verb", "note": "Regular -ar."},
    {"id": "trabajar", "es": "trabajar", "en": ["to work"], "pos": "verb", "note": "Regular -ar."},
    {"id": "alquilar", "es": "alquilar", "es_alt": ["arrendar"], "en": ["to rent"], "pos": "verb", "note": "Colombia often uses 'arrendar'."},
    {"id": "aprender", "es": "aprender", "en": ["to learn"], "pos": "verb", "note": "Regular -er."},
    {"id": "salir", "es": "salir", "en": ["to leave", "to go out"], "pos": "verb", "note": "Irregular yo: salgo."},
    {"id": "llegar", "es": "llegar", "en": ["to arrive"], "pos": "verb", "note": ""},
    {"id": "usar", "es": "usar", "en": ["to use"], "pos": "verb", "note": ""},
    {"id": "extender", "es": "extender", "en": ["to extend"], "pos": "verb", "note": "Stem change e to ie."},
    {"id": "conseguir", "es": "conseguir", "es_alt": ["recibir"], "en": ["to get", "to obtain"], "pos": "verb", "note": "conseguir = to obtain; recibir = to receive."},
    {"id": "caminar", "es": "caminar", "en": ["to walk"], "pos": "verb", "note": ""},
    {"id": "esperar", "es": "esperar", "en": ["to wait", "to hope", "to expect"], "pos": "verb", "note": ""},
    {"id": "ser", "es": "ser", "en": ["to be"], "pos": "verb", "note": "Permanent traits, identity, time. Irregular."},
    {"id": "estar", "es": "estar", "en": ["to be"], "pos": "verb", "note": "Temporary states, location. Irregular."},
    {"id": "hacer", "es": "hacer", "en": ["to do", "to make"], "pos": "verb", "note": "Irregular yo: hago."},
    {"id": "tener", "es": "tener", "en": ["to have"], "pos": "verb", "note": "Irregular: tengo, tienes."},
    {"id": "ir", "es": "ir", "en": ["to go"], "pos": "verb", "note": "Irregular: voy, vas, va."},
    {"id": "hablar", "es": "hablar", "en": ["to talk", "to speak"], "pos": "verb", "note": ""},
    {"id": "coger", "es": "coger", "en": ["to get", "to take", "to catch"], "pos": "verb", "note": "Fine in Colombia (coger el bus). Vulgar in Mexico and Argentina, so avoid there."},
    {"id": "vivir", "es": "vivir", "en": ["to live"], "pos": "verb", "note": ""},
    {"id": "traer", "es": "traer", "en": ["to bring"], "pos": "verb", "note": "Irregular yo: traigo."},
    {"id": "beber", "es": "beber", "es_alt": ["tomar"], "en": ["to drink"], "pos": "verb", "note": "Colombia usually says 'tomar' for drinking."},
    {"id": "necesitar", "es": "necesitar", "en": ["to need"], "pos": "verb", "note": ""},
    {"id": "tocar", "es": "tocar", "en": ["to touch", "to play (instrument)"], "pos": "verb", "note": ""},
    {"id": "querer", "es": "querer", "en": ["to want"], "pos": "verb", "note": "Stem change e to ie: quiero."},
    {"id": "deber", "es": "deber", "en": ["to must", "should", "to owe"], "pos": "verb", "note": ""},
    {"id": "poner", "es": "poner", "en": ["to put"], "pos": "verb", "note": "Irregular yo: pongo."},
    {"id": "buscar", "es": "buscar", "en": ["to search", "to look for"], "pos": "verb", "note": "Do not add 'for': buscar algo."},
    {"id": "encontrar", "es": "encontrar", "en": ["to find"], "pos": "verb", "note": "Stem change o to ue: encuentro."},
    {"id": "dormir", "es": "dormir", "en": ["to sleep"], "pos": "verb", "note": "Stem change o to ue: duermo."},
    {"id": "saber", "es": "saber", "en": ["to know"], "pos": "verb", "note": "Facts/how-to. Irregular yo: sé."},
    {"id": "dar", "es": "dar", "en": ["to give"], "pos": "verb", "note": "Irregular yo: doy."},
    {"id": "comer", "es": "comer", "en": ["to eat"], "pos": "verb", "note": "Regular -er."},
    {"id": "venir", "es": "venir", "en": ["to come"], "pos": "verb", "note": "Irregular: vengo, vienes."},
    {"id": "decir", "es": "decir", "en": ["to say", "to tell"], "pos": "verb", "note": "Irregular: digo, dices."},
    {"id": "prestar", "es": "prestar", "en": ["to lend"], "pos": "verb", "note": "'prestar' = to lend; 'pedir prestado' = to borrow."},
    {"id": "hambre", "es": "hambre", "en": ["hunger"], "pos": "noun", "note": "f. 'hungry' = tener hambre (to have hunger)."},
  ],
  sentences: [
    {"id": "s001", "wordId": "comer", "es": "Nosotros {comemos} a la una.", "answer": "comemos", "en": "We eat at one."},
    {"id": "s002", "wordId": "beber", "es": "No {bebo} café por la noche.", "answer": "bebo", "en": "I don't drink coffee at night."},
    {"id": "s003", "wordId": "tener", "es": "Yo {tengo} hambre.", "answer": "tengo", "en": "I'm hungry."},
    {"id": "s004", "wordId": "tener", "es": "¿{Tienes} una mesa para dos?", "answer": "Tienes", "en": "Do you have a table for two?"},
    {"id": "s005", "wordId": "estar", "es": "El baño {está} a la derecha.", "answer": "está", "en": "The bathroom is on the right."},
    {"id": "s006", "wordId": "ser", "es": "Ella {es} muy fuerte.", "answer": "es", "en": "She is very strong."},
    {"id": "s007", "wordId": "ir", "es": "Mañana {voy} a viajar.", "answer": "voy", "en": "Tomorrow I'm going to travel."},
    {"id": "s008", "wordId": "hacer", "es": "¿Qué {haces} los domingos?", "answer": "haces", "en": "What do you do on Sundays?"},
    {"id": "s009", "wordId": "hablar", "es": "Yo {hablo} un poco de español.", "answer": "hablo", "en": "I speak a little Spanish."},
    {"id": "s010", "wordId": "poder", "es": "¿{Puedes} ayudarme?", "answer": "Puedes", "en": "Can you help me?"},
    {"id": "s011", "wordId": "querer", "es": "{Quiero} una copa de vino tinto.", "answer": "Quiero", "en": "I want a glass of red wine."},
    {"id": "s012", "wordId": "necesitar", "es": "{Necesito} un vaso de agua.", "answer": "Necesito", "en": "I need a glass of water."},
    {"id": "s013", "wordId": "vivir", "es": "Yo {vivo} cerca del centro.", "answer": "vivo", "en": "I live near the centre."},
    {"id": "s014", "wordId": "trabajar", "es": "{Trabajo} todos los días.", "answer": "Trabajo", "en": "I work every day."},
    {"id": "s015", "wordId": "viajar", "es": "Me gusta {viajar} solo.", "answer": "viajar", "en": "I like to travel alone."},
    {"id": "s016", "wordId": "aprender", "es": "Quiero {aprender} español.", "answer": "aprender", "en": "I want to learn Spanish."},
    {"id": "s017", "wordId": "salir", "es": "{Salgo} de la casa a las ocho.", "answer": "Salgo", "en": "I leave the house at eight."},
    {"id": "s018", "wordId": "llegar", "es": "El bus {llega} tarde.", "answer": "llega", "en": "The bus arrives late."},
    {"id": "s019", "wordId": "esperar", "es": "Tienes que {esperar} aquí.", "answer": "esperar", "en": "You have to wait here."},
    {"id": "s020", "wordId": "pedir", "es": "Voy a {pedir} la comida.", "answer": "pedir", "en": "I'm going to order the food."},
    {"id": "s021", "wordId": "usar", "es": "¿Puedo {usar} el baño?", "answer": "usar", "en": "Can I use the bathroom?"},
    {"id": "s022", "wordId": "buscar", "es": "{Busco} un hotel cerca de la playa.", "answer": "Busco", "en": "I'm looking for a hotel near the beach."},
    {"id": "s023", "wordId": "encontrar", "es": "No {encuentro} mis llaves.", "answer": "encuentro", "en": "I can't find my keys."},
    {"id": "s024", "wordId": "dormir", "es": "{Duermo} ocho horas.", "answer": "Duermo", "en": "I sleep eight hours."},
    {"id": "s025", "wordId": "saber", "es": "No {sé} dónde está.", "answer": "sé", "en": "I don't know where it is."},
    {"id": "s026", "wordId": "dar", "es": "¿Me {das} la cuenta?", "answer": "das", "en": "Can you give me the bill?"},
    {"id": "s027", "wordId": "venir", "es": "¿{Vienes} conmigo?", "answer": "Vienes", "en": "Are you coming with me?"},
    {"id": "s028", "wordId": "decir", "es": "¿Qué {dices}?", "answer": "dices", "en": "What are you saying?"},
    {"id": "s029", "wordId": "traer", "es": "¿Me {traes} agua, por favor?", "answer": "traes", "en": "Can you bring me water, please?"},
    {"id": "s030", "wordId": "poner", "es": "{Pongo} la bolsa en la mesa.", "answer": "Pongo", "en": "I put the bag on the table."},
    {"id": "s031", "wordId": "tocar", "es": "¿{Tocas} la guitarra?", "answer": "Tocas", "en": "Do you play the guitar?"},
    {"id": "s032", "wordId": "deber", "es": "{Debo} pagar con tarjeta.", "answer": "Debo", "en": "I must pay by card."},
    {"id": "s033", "wordId": "caminar", "es": "Me gusta {caminar} por la calle.", "answer": "caminar", "en": "I like to walk along the street."},
    {"id": "s034", "wordId": "alquilar", "es": "Quiero {alquilar} un cuarto.", "answer": "alquilar", "en": "I want to rent a room."},
    {"id": "s035", "wordId": "conseguir", "es": "¿Dónde puedo {conseguir} un taxi?", "answer": "conseguir", "en": "Where can I get a taxi?"},
    {"id": "s036", "wordId": "prestar", "es": "¿Me {prestas} tu teléfono?", "answer": "prestas", "en": "Can you lend me your phone?"},
    {"id": "s037", "wordId": "extender", "es": "Quiero {extender} mi estadía.", "answer": "extender", "en": "I want to extend my stay."},
    {"id": "s038", "wordId": "coger", "es": "Tengo que {coger} el bus.", "answer": "coger", "en": "I have to catch the bus."},
    {"id": "s039", "wordId": "cama", "es": "La {cama} es muy cómoda.", "answer": "cama", "en": "The bed is very comfortable."},
    {"id": "s040", "wordId": "habitacion", "es": "Mi {habitación} tiene baño.", "answer": "habitación", "en": "My room has a bathroom."},
    {"id": "s041", "wordId": "bano", "es": "¿Dónde está el {baño}?", "answer": "baño", "en": "Where is the bathroom?"},
    {"id": "s042", "wordId": "agua", "es": "Un vaso de {agua}, por favor.", "answer": "agua", "en": "A glass of water, please."},
    {"id": "s043", "wordId": "comida", "es": "La {comida} está muy rica.", "answer": "comida", "en": "The food is very good."},
    {"id": "s044", "wordId": "mesa", "es": "¿Hay una {mesa} libre?", "answer": "mesa", "en": "Is there a free table?"},
    {"id": "s045", "wordId": "calle", "es": "Vivo en esta {calle}.", "answer": "calle", "en": "I live on this street."},
    {"id": "s046", "wordId": "caneca", "es": "¿Dónde está la {caneca}?", "answer": "caneca", "en": "Where is the bin?"},
    {"id": "s047", "wordId": "bolsa", "es": "Necesito una {bolsa}, por favor.", "answer": "bolsa", "en": "I need a bag, please."},
    {"id": "s048", "wordId": "tinto", "es": "Un {tinto}, por favor.", "answer": "tinto", "en": "A black coffee, please. (Colombia)"},
    {"id": "s049", "wordId": "tocineta", "es": "Quiero huevos con {tocineta}.", "answer": "tocineta", "en": "I want eggs with bacon."},
    {"id": "s050", "wordId": "salida", "es": "¿A qué hora es la {salida}?", "answer": "salida", "en": "What time is checkout?"},
    {"id": "s051", "wordId": "cansado", "es": "Estoy muy {cansado} hoy.", "answer": "cansado", "en": "I'm very tired today."},
    {"id": "s052", "wordId": "feliz", "es": "Estoy {feliz} de estar aquí.", "answer": "feliz", "en": "I'm happy to be here."},
    {"id": "s053", "wordId": "triste", "es": "Ella está {triste}.", "answer": "triste", "en": "She is sad."},
    {"id": "s054", "wordId": "fuerte", "es": "El café está muy {fuerte}.", "answer": "fuerte", "en": "The coffee is very strong."},
    {"id": "s055", "wordId": "abierto", "es": "¿Está {abierto} el restaurante?", "answer": "abierto", "en": "Is the restaurant open?"},
    {"id": "s056", "wordId": "cerrado", "es": "La tienda está {cerrada}.", "answer": "cerrada", "en": "The shop is closed."},
    {"id": "s057", "wordId": "listo", "es": "La comida está {lista}.", "answer": "lista", "en": "The food is ready."},
    {"id": "s058", "wordId": "mejor", "es": "Este es el {mejor} café de la ciudad.", "answer": "mejor", "en": "This is the best coffee in the city."},
    {"id": "s059", "wordId": "peor", "es": "Hoy es el {peor} día.", "answer": "peor", "en": "Today is the worst day."},
    {"id": "s060", "wordId": "mismo", "es": "Quiero lo {mismo}, por favor.", "answer": "mismo", "en": "I want the same, please."},
    {"id": "s061", "wordId": "diferente", "es": "Quiero algo {diferente}.", "answer": "diferente", "en": "I want something different."},
    {"id": "s062", "wordId": "lleno", "es": "El vaso está {lleno}.", "answer": "lleno", "en": "The glass is full."},
    {"id": "s063", "wordId": "izquierda", "es": "Gira a la {izquierda}.", "answer": "izquierda", "en": "Turn left."},
    {"id": "s064", "wordId": "derecha", "es": "El baño está a la {derecha}.", "answer": "derecha", "en": "The bathroom is on the right."},
    {"id": "s065", "wordId": "arriba", "es": "Mi cuarto está {arriba}.", "answer": "arriba", "en": "My room is upstairs."},
    {"id": "s066", "wordId": "abajo", "es": "El bar está {abajo}.", "answer": "abajo", "en": "The bar is downstairs."},
    {"id": "s067", "wordId": "aqui", "es": "Ven {aquí}, por favor.", "answer": "aquí", "en": "Come here, please."},
    {"id": "s068", "wordId": "alli", "es": "El taxi está {allí}.", "answer": "allí", "en": "The taxi is there."},
    {"id": "s069", "wordId": "afuera", "es": "Te espero {afuera}.", "answer": "afuera", "en": "I'll wait for you outside."},
    {"id": "s070", "wordId": "adentro", "es": "Podemos comer {adentro}.", "answer": "adentro", "en": "We can eat inside."},
    {"id": "s071", "wordId": "cerca", "es": "El hotel está {cerca}.", "answer": "cerca", "en": "The hotel is near."},
    {"id": "s072", "wordId": "lejos", "es": "La playa está {lejos}.", "answer": "lejos", "en": "The beach is far."},
    {"id": "s073", "wordId": "casi", "es": "{Casi} llegamos.", "answer": "Casi", "en": "We're almost there."},
    {"id": "s074", "wordId": "lunes", "es": "Hoy es {lunes}.", "answer": "lunes", "en": "Today is Monday."},
    {"id": "s075", "wordId": "viernes", "es": "El {viernes} salgo temprano.", "answer": "viernes", "en": "On Friday I leave early."},
    {"id": "s076", "wordId": "domingo", "es": "Los {domingos} descanso.", "answer": "domingos", "en": "On Sundays I rest."},
    {"id": "s077", "wordId": "cuanto", "es": "¿{Cuánto} cuesta?", "answer": "Cuánto", "en": "How much is it?"},
    {"id": "s078", "wordId": "cuando", "es": "¿{Cuándo} llegas?", "answer": "Cuándo", "en": "When do you arrive?"},
    {"id": "s079", "wordId": "donde", "es": "¿{Dónde} está la salida?", "answer": "Dónde", "en": "Where is the exit?"},
    {"id": "s080", "wordId": "quien", "es": "¿{Quién} es?", "answer": "Quién", "en": "Who is it?"},
    {"id": "s081", "wordId": "como", "es": "¿{Cómo} estás?", "answer": "Cómo", "en": "How are you?"},
    {"id": "s082", "wordId": "por-que", "es": "¿{Por qué} no vienes?", "answer": "Por qué", "en": "Why don't you come?"},
    {"id": "s083", "wordId": "a-que-hora", "es": "¿{A qué hora} sale el bus?", "answer": "A qué hora", "en": "What time does the bus leave?"},
    {"id": "s084", "wordId": "cada-cuanto", "es": "¿{Cada cuánto} pasa el bus?", "answer": "Cada cuánto", "en": "How often does the bus come?"},
    {"id": "s085", "wordId": "para", "es": "Esto es {para} ti.", "answer": "para", "en": "This is for you."},
    {"id": "s086", "wordId": "por", "es": "Gracias {por} todo.", "answer": "por", "en": "Thanks for everything."},
    {"id": "s087", "wordId": "desde", "es": "Trabajo aquí {desde} enero.", "answer": "desde", "en": "I've worked here since January."},
    {"id": "s088", "wordId": "entonces", "es": "No tengo dinero, {entonces} no voy.", "answer": "entonces", "en": "I don't have money, so I'm not going."},
    {"id": "s089", "wordId": "nosotros", "es": "{Nosotros} queremos la cuenta.", "answer": "Nosotros", "en": "We want the bill."},
    {"id": "s090", "wordId": "vez", "es": "Es la primera {vez} que vengo.", "answer": "vez", "en": "It's the first time I've come."},
    {"id": "s091", "wordId": "con-tarjeta", "es": "¿Puedo pagar {con tarjeta}?", "answer": "con tarjeta", "en": "Can I pay by card?"},
    {"id": "s092", "wordId": "en-efectivo", "es": "Prefiero pagar {en efectivo}.", "answer": "en efectivo", "en": "I prefer to pay in cash."},
    {"id": "s093", "wordId": "algo-mas", "es": "¿{Algo más}?", "answer": "Algo más", "en": "Anything else?"},
    {"id": "s094", "wordId": "hasta-luego", "es": "Nos vemos, ¡{hasta luego}!", "answer": "hasta luego", "en": "See you, later!"},
    {"id": "s095", "wordId": "por-supuesto", "es": "Claro, ¡{por supuesto}!", "answer": "por supuesto", "en": "Sure, of course!"},
    {"id": "s096", "wordId": "de-nada", "es": "Gracias. {De nada}.", "answer": "De nada", "en": "Thanks. You're welcome."},
    {"id": "s097", "wordId": "dime", "es": "{Dime}, ¿qué necesitas?", "answer": "Dime", "en": "Tell me, what do you need?"},
    {"id": "s098", "wordId": "placer", "es": "Fue un {placer}.", "answer": "placer", "en": "It was a pleasure."},
    {"id": "s099", "wordId": "hambre", "es": "Tengo mucha {hambre}.", "answer": "hambre", "en": "I'm very hungry."},
    {"id": "s100", "wordId": "hay-un", "es": "¿{Hay un} cajero cerca?", "answer": "Hay un", "en": "Is there an ATM near?"},
  ],
};
