/* The generated bank: vocabulary and example sentences.

   Written for this app rather than supplied with it, which is why it is not
   in seed.js; that file is the original bank and stays as it was given. Both
   are loaded and merged, and a word added through the Manage screen sits on
   top of them both.

   Every word carries its own topic, so nothing here needs a second entry in
   topics.js. Every sentence wraps the target form in {braces}; the cloze card
   blanks it out and the answer is the form as written, inflected, because the
   learner types what the sentence needs rather than the dictionary form.

   252 words, 285 sentences. Generated in batches and
   checked by tests/test-bank.mjs, which fails on a duplicate, a missing
   field, an unknown topic, or a braced form that is not a form of its word.
   Those checks settle structure, not meaning: the Spanish has been written
   with care but has not been read by a native speaker, so treat a surprising
   translation as a bug worth reporting rather than as gospel.

   vocabulary: { id, es, es_alt[], en[], pos, topic, note }
   sentences:  { id, wordId, es, answer, en }
*/
const VOCAB = {
  vocabulary: [
    {"id":"hombre","es":"hombre","en":["man"],"pos":"noun","topic":"people","note":"m."},
    {"id":"mujer","es":"mujer","en":["woman"],"pos":"noun","topic":"people","note":"f. Plural mujeres."},
    {"id":"nino","es":"niño","en":["boy","child"],"pos":"noun","topic":"people","note":"m. niña for a girl."},
    {"id":"nina","es":"niña","en":["girl"],"pos":"noun","topic":"people","note":"f."},
    {"id":"gente","es":"gente","en":["people"],"pos":"noun","topic":"people","note":"f. and singular: la gente es, never la gente son."},
    {"id":"persona","es":"persona","en":["person"],"pos":"noun","topic":"people","note":"f. even for a man: esa persona."},
    {"id":"amigo","es":"amigo","en":["friend"],"pos":"noun","topic":"people","note":"m. amiga for a woman."},
    {"id":"familia","es":"familia","en":["family"],"pos":"noun","topic":"people","note":"f."},
    {"id":"madre","es":"madre","en":["mother"],"pos":"noun","topic":"people","note":"f. Everyday Colombian is mamá."},
    {"id":"padre","es":"padre","en":["father"],"pos":"noun","topic":"people","note":"m. Everyday Colombian is papá. Plural padres means parents."},
    {"id":"hijo","es":"hijo","en":["son"],"pos":"noun","topic":"people","note":"m. hija for a daughter; hijos for children generally."},
    {"id":"hermano","es":"hermano","en":["brother"],"pos":"noun","topic":"people","note":"m. hermana for a sister."},
    {"id":"hermana","es":"hermana","en":["sister"],"pos":"noun","topic":"people","note":"f."},
    {"id":"esposo","es":"esposo","en":["husband"],"pos":"noun","topic":"people","note":"m. esposa for a wife. Marido also means husband."},
    {"id":"novio","es":"novio","en":["boyfriend"],"pos":"noun","topic":"people","note":"m. novia for a girlfriend; also groom and bride."},
    {"id":"abuelo","es":"abuelo","en":["grandfather"],"pos":"noun","topic":"people","note":"m. abuela for a grandmother."},
    {"id":"senor","es":"señor","en":["sir","mister","gentleman"],"pos":"noun","topic":"people","note":"m. How you address a man you do not know."},
    {"id":"senora","es":"señora","en":["madam","missus","lady"],"pos":"noun","topic":"people","note":"f. Señorita for a younger woman, though it is going out of use."},
    {"id":"vecino","es":"vecino","en":["neighbour"],"pos":"noun","topic":"people","note":"m. vecina for a woman."},
    {"id":"yo","es":"yo","en":["i"],"pos":"pronoun","topic":"people","note":"Usually dropped: the verb ending already says who."},
    {"id":"el-pron","es":"él","en":["he","him"],"pos":"pronoun","topic":"people","note":"The accent separates it from el, the."},
    {"id":"ella","es":"ella","en":["she","her"],"pos":"pronoun","topic":"people"},
    {"id":"ellos","es":"ellos","en":["they"],"pos":"pronoun","topic":"people","note":"ellas if the group is all women."},
    {"id":"usted","es":"usted","en":["you"],"pos":"pronoun","topic":"people","note":"The polite you, and the everyday one in much of Colombia. Takes él verb forms."},
    {"id":"ustedes","es":"ustedes","en":["you all","you"],"pos":"pronoun","topic":"people","note":"The only you-plural in Latin America, polite or not."},
    {"id":"me","es":"me","en":["me","myself"],"pos":"pronoun","topic":"people","note":"Goes before the verb: me llamo, me gusta."},
    {"id":"te","es":"te","en":["you"],"pos":"pronoun","topic":"people","note":"The object form of tú."},
    {"id":"le","es":"le","en":["to him","to her","to you"],"pos":"pronoun","topic":"people","note":"The indirect object: le dije, I told him."},
    {"id":"nos","es":"nos","en":["us"],"pos":"pronoun","topic":"people"},
    {"id":"su","es":"su","en":["his","her","their","your"],"pos":"determiner","topic":"people","note":"One word for all of them; context decides. sus before a plural noun."},
    {"id":"ver","es":"ver","en":["to see","to watch"],"pos":"verb","topic":"verbs","note":"yo veo. Past participle visto."},
    {"id":"pensar","es":"pensar","en":["to think"],"pos":"verb","topic":"verbs","note":"e to ie: pienso. pensar en, to think about."},
    {"id":"creer","es":"creer","en":["to believe","to think"],"pos":"verb","topic":"verbs","note":"creo que is the everyday I think."},
    {"id":"gustar","es":"gustar","en":["to like","to please"],"pos":"verb","topic":"verbs","note":"Backwards: me gusta el café is the coffee pleases me. The thing liked is the subject."},
    {"id":"empezar","es":"empezar","en":["to start","to begin"],"pos":"verb","topic":"verbs","note":"e to ie: empiezo. Comenzar is the same thing."},
    {"id":"terminar","es":"terminar","en":["to finish","to end"],"pos":"verb","topic":"verbs","note":"Regular. Acabar also works."},
    {"id":"seguir","es":"seguir","en":["to follow","to carry on"],"pos":"verb","topic":"verbs","note":"e to i: sigo. seguir + gerund means to keep doing."},
    {"id":"volver","es":"volver","en":["to return","to come back"],"pos":"verb","topic":"verbs","note":"o to ue: vuelvo. Past participle vuelto."},
    {"id":"llevar","es":"llevar","en":["to carry","to take","to wear"],"pos":"verb","topic":"verbs","note":"Take something away from here; traer is bring towards here."},
    {"id":"dejar","es":"dejar","en":["to leave","to let"],"pos":"verb","topic":"verbs","note":"Leave a thing behind. dejar de + infinitive is to stop doing."},
    {"id":"pasar","es":"pasar","en":["to pass","to happen","to spend time"],"pos":"verb","topic":"verbs","note":"¿Qué pasó? is what happened."},
    {"id":"quedar","es":"quedar","en":["to stay","to be left","to arrange to meet"],"pos":"verb","topic":"verbs","note":"quedarse is to stay somewhere; queda cerca is it is nearby."},
    {"id":"parecer","es":"parecer","en":["to seem","to look like"],"pos":"verb","topic":"verbs","note":"yo parezco. ¿Qué te parece? is what do you think."},
    {"id":"sentir","es":"sentir","en":["to feel","to be sorry"],"pos":"verb","topic":"verbs","note":"e to ie: siento. Lo siento is I am sorry."},
    {"id":"entender","es":"entender","en":["to understand"],"pos":"verb","topic":"verbs","note":"e to ie: entiendo. Comprender is the same thing."},
    {"id":"escribir","es":"escribir","en":["to write"],"pos":"verb","topic":"verbs","note":"Past participle escrito, irregular."},
    {"id":"leer","es":"leer","en":["to read"],"pos":"verb","topic":"verbs","note":"Third person past is leyó, with a y."},
    {"id":"escuchar","es":"escuchar","en":["to listen","to hear"],"pos":"verb","topic":"verbs","note":"Listening on purpose; oír is hearing whether you meant to or not."},
    {"id":"mirar","es":"mirar","en":["to look","to watch"],"pos":"verb","topic":"verbs","note":"Looking on purpose; ver is seeing."},
    {"id":"abrir","es":"abrir","en":["to open"],"pos":"verb","topic":"verbs","note":"Past participle abierto, irregular."},
    {"id":"cerrar","es":"cerrar","en":["to close","to shut"],"pos":"verb","topic":"verbs","note":"e to ie: cierro."},
    {"id":"comprar","es":"comprar","en":["to buy"],"pos":"verb","topic":"verbs","note":"Regular."},
    {"id":"vender","es":"vender","en":["to sell"],"pos":"verb","topic":"verbs","note":"Regular."},
    {"id":"pagar","es":"pagar","en":["to pay"],"pos":"verb","topic":"verbs","note":"Spelling change in the past: pagué."},
    {"id":"ayudar","es":"ayudar","en":["to help"],"pos":"verb","topic":"verbs","note":"Regular. ¿Le ayudo? is can I help you."},
    {"id":"jugar","es":"jugar","en":["to play"],"pos":"verb","topic":"verbs","note":"u to ue, unique: juego. Games and sport only; tocar for instruments."},
    {"id":"cocinar","es":"cocinar","en":["to cook"],"pos":"verb","topic":"verbs","note":"Regular."},
    {"id":"correr","es":"correr","en":["to run"],"pos":"verb","topic":"verbs","note":"Regular."},
    {"id":"llorar","es":"llorar","en":["to cry"],"pos":"verb","topic":"verbs","note":"Regular."},
    {"id":"reir","es":"reír","en":["to laugh"],"pos":"verb","topic":"verbs","note":"yo río. Usually reflexive: reírse de algo."},
    {"id":"olvidar","es":"olvidar","en":["to forget"],"pos":"verb","topic":"verbs","note":"Often reflexive: se me olvidó, it got forgotten on me."},
    {"id":"recordar","es":"recordar","en":["to remember","to remind"],"pos":"verb","topic":"verbs","note":"o to ue: recuerdo."},
    {"id":"cambiar","es":"cambiar","en":["to change"],"pos":"verb","topic":"verbs","note":"Regular."},
    {"id":"mandar","es":"mandar","en":["to send","to order"],"pos":"verb","topic":"verbs","note":"Enviar also means send."},
    {"id":"preguntar","es":"preguntar","en":["to ask"],"pos":"verb","topic":"verbs","note":"Ask a question. pedir is ask for a thing."},
    {"id":"contestar","es":"contestar","en":["to answer","to reply"],"pos":"verb","topic":"verbs","note":"Responder is the same thing."},
    {"id":"esperar-verbo","es":"aguardar","en":["to wait","to await"],"pos":"verb","topic":"verbs","note":"Formal. Esperar is the everyday word for wait."},
    {"id":"intentar","es":"intentar","en":["to try"],"pos":"verb","topic":"verbs","note":"Tratar de is the same thing."},
    {"id":"ganar","es":"ganar","en":["to win","to earn"],"pos":"verb","topic":"verbs","note":"Both winning and being paid."},
    {"id":"perder","es":"perder","en":["to lose","to miss"],"pos":"verb","topic":"verbs","note":"e to ie: pierdo. Also missing a bus or a flight."},
    {"id":"y","es":"y","en":["and"],"pos":"conjunction","topic":"glue","note":"Becomes e before a word starting with i or hi: padre e hijo."},
    {"id":"o","es":"o","en":["or"],"pos":"conjunction","topic":"glue","note":"Becomes u before a word starting with o or ho."},
    {"id":"pero","es":"pero","en":["but"],"pos":"conjunction","topic":"glue"},
    {"id":"porque","es":"porque","en":["because"],"pos":"conjunction","topic":"glue","note":"One word, no accent. ¿Por qué? with two is the question."},
    {"id":"si-cond","es":"si","en":["if"],"pos":"conjunction","topic":"glue","note":"No accent. Sí with one means yes."},
    {"id":"aunque","es":"aunque","en":["although","even though"],"pos":"conjunction","topic":"glue"},
    {"id":"tambien","es":"también","en":["also","too","as well"],"pos":"adverb","topic":"glue","note":"For agreeing with a positive. Tampoco is the negative version."},
    {"id":"tampoco","es":"tampoco","en":["neither","not either"],"pos":"adverb","topic":"glue","note":"Agreeing with a negative: yo tampoco, me neither."},
    {"id":"muy","es":"muy","en":["very"],"pos":"adverb","topic":"glue","note":"Goes before adjectives. Mucho goes with nouns and verbs."},
    {"id":"mucho","es":"mucho","en":["a lot","much","many"],"pos":"adverb","topic":"glue","note":"Agrees when it describes a noun: muchas cosas."},
    {"id":"poco","es":"poco","en":["little","few","not much"],"pos":"adverb","topic":"glue","note":"un poco is a bit; poco on its own leans negative."},
    {"id":"mas","es":"más","en":["more","most"],"pos":"adverb","topic":"glue","note":"Accented. más que is more than."},
    {"id":"menos","es":"menos","en":["less","fewer","except"],"pos":"adverb","topic":"glue","note":"Also does minus, and to tell the time: diez menos cuarto."},
    {"id":"tanto","es":"tanto","en":["so much","so many"],"pos":"adverb","topic":"glue","note":"tan before an adjective: tan bueno."},
    {"id":"siempre","es":"siempre","en":["always"],"pos":"adverb","topic":"glue"},
    {"id":"nunca","es":"nunca","en":["never"],"pos":"adverb","topic":"glue","note":"A double negative is correct: no voy nunca."},
    {"id":"ya","es":"ya","en":["already","now","any more"],"pos":"adverb","topic":"glue","note":"Very common and slippery. ya no is not any more; ya voy is I am coming."},
    {"id":"todavia","es":"todavía","en":["still","yet"],"pos":"adverb","topic":"glue","note":"Aún means the same."},
    {"id":"tal-vez","es":"tal vez","en":["maybe","perhaps"],"pos":"phrase","topic":"glue","note":"Quizás and a lo mejor do the same job."},
    {"id":"solo","es":"solo","en":["only","just","alone"],"pos":"adverb","topic":"glue","note":"Solamente is the longer form of only."},
    {"id":"bien","es":"bien","en":["well","fine","okay"],"pos":"adverb","topic":"glue","note":"An adverb. bueno is the adjective; estoy bien, not estoy bueno."},
    {"id":"mal","es":"mal","en":["badly","wrong"],"pos":"adverb","topic":"glue","note":"The adverb of malo. Me siento mal is I feel unwell."},
    {"id":"asi","es":"así","en":["like this","that way","so"],"pos":"adverb","topic":"glue","note":"así que means so, therefore."},
    {"id":"sin","es":"sin","en":["without"],"pos":"preposition","topic":"glue","note":"Followed by the infinitive: sin pensar."},
    {"id":"con","es":"con","en":["with"],"pos":"preposition","topic":"glue","note":"conmigo and contigo are one word: with me, with you."},
    {"id":"sobre","es":"sobre","en":["on","about","over"],"pos":"preposition","topic":"glue","note":"Also a noun: un sobre is an envelope."},
    {"id":"entre","es":"entre","en":["between","among"],"pos":"preposition","topic":"glue"},
    {"id":"hasta","es":"hasta","en":["until","up to","as far as"],"pos":"preposition","topic":"glue","note":"Also does even: hasta yo lo sé."},
    {"id":"durante","es":"durante","en":["during","for"],"pos":"preposition","topic":"glue","note":"For a length of time: durante dos horas."},
    {"id":"antes","es":"antes","en":["before","beforehand"],"pos":"adverb","topic":"glue","note":"antes de + infinitive: antes de salir."},
    {"id":"despues","es":"después","en":["after","afterwards","later"],"pos":"adverb","topic":"glue","note":"después de + infinitive."},
    {"id":"nada","es":"nada","en":["nothing","anything"],"pos":"pronoun","topic":"glue","note":"With no before the verb: no quiero nada."},
    {"id":"nadie","es":"nadie","en":["nobody","anybody"],"pos":"pronoun","topic":"glue"},
    {"id":"algo","es":"algo","en":["something","anything"],"pos":"pronoun","topic":"glue"},
    {"id":"alguien","es":"alguien","en":["somebody","someone"],"pos":"pronoun","topic":"glue"},
    {"id":"todo","es":"todo","en":["all","everything"],"pos":"pronoun","topic":"glue","note":"todos means everybody. Agrees: toda la noche."},
    {"id":"otro","es":"otro","en":["other","another"],"pos":"determiner","topic":"glue","note":"Never un otro; just otro."},
    {"id":"cada","es":"cada","en":["each","every"],"pos":"determiner","topic":"glue","note":"Never changes for gender."},
    {"id":"mientras","es":"mientras","en":["while","meanwhile"],"pos":"conjunction","topic":"glue","note":"mientras tanto is meanwhile."},
    {"id":"claro","es":"claro","en":["of course","sure","clear"],"pos":"adverb","topic":"glue","note":"Claro que sí is an emphatic yes. Also the adjective for light in colour."},
    {"id":"casa","es":"casa","en":["house","home"],"pos":"noun","topic":"home","note":"f. en casa is at home, with no article."},
    {"id":"puerta","es":"puerta","en":["door"],"pos":"noun","topic":"home","note":"f."},
    {"id":"ventana","es":"ventana","en":["window"],"pos":"noun","topic":"home","note":"f."},
    {"id":"llave","es":"llave","en":["key"],"pos":"noun","topic":"home","note":"f. Also a tap in some countries."},
    {"id":"silla","es":"silla","en":["chair"],"pos":"noun","topic":"home","note":"f."},
    {"id":"cocina","es":"cocina","en":["kitchen","cooker"],"pos":"noun","topic":"home","note":"f. Both the room and the stove."},
    {"id":"ropa","es":"ropa","en":["clothes"],"pos":"noun","topic":"home","note":"f. and singular: la ropa está sucia."},
    {"id":"luz","es":"luz","en":["light","electricity"],"pos":"noun","topic":"home","note":"f. Plural luces. Also the electricity bill."},
    {"id":"pan","es":"pan","en":["bread"],"pos":"noun","topic":"food","note":"m."},
    {"id":"arroz","es":"arroz","en":["rice"],"pos":"noun","topic":"food","note":"m. On the side of almost everything in Colombia."},
    {"id":"carne","es":"carne","en":["meat"],"pos":"noun","topic":"food","note":"f."},
    {"id":"pollo","es":"pollo","en":["chicken"],"pos":"noun","topic":"food","note":"m."},
    {"id":"huevo","es":"huevo","en":["egg"],"pos":"noun","topic":"food","note":"m."},
    {"id":"fruta","es":"fruta","en":["fruit"],"pos":"noun","topic":"food","note":"f."},
    {"id":"leche","es":"leche","en":["milk"],"pos":"noun","topic":"food","note":"f."},
    {"id":"cerveza","es":"cerveza","en":["beer"],"pos":"noun","topic":"food","note":"f."},
    {"id":"jugo","es":"jugo","en":["juice"],"pos":"noun","topic":"food","note":"m. Zumo in Spain."},
    {"id":"azucar","es":"azúcar","en":["sugar"],"pos":"noun","topic":"food","note":"m. usually, though you will hear both."},
    {"id":"sal","es":"sal","en":["salt"],"pos":"noun","topic":"food","note":"f. Also the tú command of salir."},
    {"id":"sopa","es":"sopa","en":["soup"],"pos":"noun","topic":"food","note":"f."},
    {"id":"desayuno","es":"desayuno","en":["breakfast"],"pos":"noun","topic":"food","note":"m. desayunar is the verb."},
    {"id":"almuerzo","es":"almuerzo","en":["lunch"],"pos":"noun","topic":"food","note":"m. The main meal of the day in Colombia."},
    {"id":"cena","es":"cena","en":["dinner","supper"],"pos":"noun","topic":"food","note":"f. Comida can also mean the evening meal."},
    {"id":"cuenta","es":"cuenta","en":["bill","account"],"pos":"noun","topic":"paying","note":"f. La cuenta, por favor is how you ask for the bill."},
    {"id":"dinero","es":"dinero","en":["money"],"pos":"noun","topic":"paying","note":"m. Plata is the everyday Colombian word."},
    {"id":"plata","es":"plata","en":["money","silver"],"pos":"noun","topic":"paying","note":"f. What Colombians actually say for money."},
    {"id":"precio","es":"precio","en":["price"],"pos":"noun","topic":"paying","note":"m."},
    {"id":"tienda","es":"tienda","en":["shop","store"],"pos":"noun","topic":"paying","note":"f. A small corner shop in Colombia."},
    {"id":"mercado","es":"mercado","en":["market"],"pos":"noun","topic":"paying","note":"m. Hacer mercado is to do the food shop."},
    {"id":"ciudad","es":"ciudad","en":["city","town"],"pos":"noun","topic":"travel","note":"f."},
    {"id":"pais","es":"país","en":["country"],"pos":"noun","topic":"travel","note":"m. The accent breaks the vowels apart: pa-ís."},
    {"id":"mundo","es":"mundo","en":["world"],"pos":"noun","topic":"travel","note":"m. Todo el mundo means everybody."},
    {"id":"lugar","es":"lugar","en":["place"],"pos":"noun","topic":"travel","note":"m. Sitio means the same."},
    {"id":"carro","es":"carro","en":["car"],"pos":"noun","topic":"travel","note":"m. Coche in Spain, auto further south."},
    {"id":"bus","es":"bus","en":["bus"],"pos":"noun","topic":"travel","note":"m. Also autobús, and buseta for a small one."},
    {"id":"avion","es":"avión","en":["plane","aeroplane"],"pos":"noun","topic":"travel","note":"m. Plural aviones, no accent."},
    {"id":"viaje","es":"viaje","en":["trip","journey"],"pos":"noun","topic":"travel","note":"m. Buen viaje is have a good trip."},
    {"id":"maleta","es":"maleta","en":["suitcase","bag"],"pos":"noun","topic":"travel","note":"f."},
    {"id":"boleto","es":"boleto","en":["ticket"],"pos":"noun","topic":"travel","note":"m. Tiquete and pasaje are also used in Colombia."},
    {"id":"hotel","es":"hotel","en":["hotel"],"pos":"noun","topic":"travel","note":"m."},
    {"id":"aeropuerto","es":"aeropuerto","en":["airport"],"pos":"noun","topic":"travel","note":"m."},
    {"id":"trabajo","es":"trabajo","en":["work","job"],"pos":"noun","topic":"work","note":"m."},
    {"id":"oficina","es":"oficina","en":["office"],"pos":"noun","topic":"work","note":"f."},
    {"id":"empresa","es":"empresa","en":["company","business"],"pos":"noun","topic":"work","note":"f."},
    {"id":"reunion","es":"reunión","en":["meeting"],"pos":"noun","topic":"work","note":"f. Plural reuniones, no accent."},
    {"id":"jefe","es":"jefe","en":["boss"],"pos":"noun","topic":"work","note":"m. jefa for a woman."},
    {"id":"estudiar","es":"estudiar","en":["to study"],"pos":"verb","topic":"work","note":"Regular."},
    {"id":"clase","es":"clase","en":["class","lesson","kind"],"pos":"noun","topic":"work","note":"f. Also means sort: qué clase de."},
    {"id":"palabra","es":"palabra","en":["word"],"pos":"noun","topic":"work","note":"f."},
    {"id":"pregunta","es":"pregunta","en":["question"],"pos":"noun","topic":"work","note":"f. hacer una pregunta is to ask a question."},
    {"id":"problema","es":"problema","en":["problem"],"pos":"noun","topic":"work","note":"m. despite the a: el problema. Same for tema and sistema."},
    {"id":"cosa","es":"cosa","en":["thing"],"pos":"noun","topic":"glue","note":"f. Does an enormous amount of work in Spanish."},
    {"id":"bueno","es":"bueno","en":["good"],"pos":"adjective","topic":"describing","note":"Shortens to buen before a masculine noun: un buen día."},
    {"id":"malo","es":"malo","en":["bad"],"pos":"adjective","topic":"describing","note":"Shortens to mal before a masculine noun."},
    {"id":"grande","es":"grande","en":["big","large","great"],"pos":"adjective","topic":"describing","note":"Shortens to gran before any singular noun, where it means great rather than big."},
    {"id":"pequeno","es":"pequeño","en":["small","little"],"pos":"adjective","topic":"describing","note":"Chiquito is the everyday Colombian word."},
    {"id":"nuevo","es":"nuevo","en":["new"],"pos":"adjective","topic":"describing","note":"Before the noun it leans towards another rather than brand new."},
    {"id":"viejo","es":"viejo","en":["old"],"pos":"adjective","topic":"describing","note":"Blunt about people; mayor is the polite word for an older person."},
    {"id":"joven","es":"joven","en":["young"],"pos":"adjective","topic":"describing","note":"Plural jóvenes, which gains an accent."},
    {"id":"largo","es":"largo","en":["long"],"pos":"adjective","topic":"describing","note":"A false friend: it means long, not large."},
    {"id":"corto","es":"corto","en":["short"],"pos":"adjective","topic":"describing","note":"For length. bajo is short in height."},
    {"id":"alto","es":"alto","en":["tall","high","loud"],"pos":"adjective","topic":"describing","note":"Also does volume: habla más alto."},
    {"id":"bajo","es":"bajo","en":["short","low"],"pos":"adjective","topic":"describing","note":"Also a preposition meaning under."},
    {"id":"caro","es":"caro","en":["expensive"],"pos":"adjective","topic":"paying"},
    {"id":"barato","es":"barato","en":["cheap"],"pos":"adjective","topic":"paying","note":"Económico is the politer word."},
    {"id":"facil","es":"fácil","en":["easy"],"pos":"adjective","topic":"describing","note":"Plural fáciles."},
    {"id":"dificil","es":"difícil","en":["hard","difficult"],"pos":"adjective","topic":"describing","note":"Plural difíciles."},
    {"id":"rapido","es":"rápido","en":["fast","quick","quickly"],"pos":"adjective","topic":"describing","note":"Doubles as the adverb: camina rápido."},
    {"id":"lento","es":"lento","en":["slow"],"pos":"adjective","topic":"describing","note":"Despacio is the adverb you will hear more."},
    {"id":"caliente","es":"caliente","en":["hot"],"pos":"adjective","topic":"describing","note":"For things. For weather use hace calor, and for a person estar caliente means something else entirely."},
    {"id":"frio","es":"frío","en":["cold"],"pos":"adjective","topic":"describing","note":"Also a noun: hace frío, it is cold; tengo frío, I am cold."},
    {"id":"limpio","es":"limpio","en":["clean"],"pos":"adjective","topic":"describing","note":"limpiar is the verb."},
    {"id":"sucio","es":"sucio","en":["dirty"],"pos":"adjective","topic":"describing"},
    {"id":"bonito","es":"bonito","en":["pretty","nice","lovely"],"pos":"adjective","topic":"describing","note":"Lindo is more common in Colombia."},
    {"id":"feo","es":"feo","en":["ugly","nasty"],"pos":"adjective","topic":"describing","note":"Also used for weather and situations."},
    {"id":"importante","es":"importante","en":["important"],"pos":"adjective","topic":"describing","note":"Same for both genders."},
    {"id":"posible","es":"posible","en":["possible"],"pos":"adjective","topic":"describing","note":"lo antes posible is as soon as possible."},
    {"id":"seguro","es":"seguro","en":["sure","safe"],"pos":"adjective","topic":"describing","note":"Also a noun: insurance."},
    {"id":"amarillo","es":"amarillo","en":["yellow"],"pos":"adjective","topic":"describing","note":"Colours go after the noun and agree: la casa amarilla."},
    {"id":"rojo","es":"rojo","en":["red"],"pos":"adjective","topic":"describing"},
    {"id":"verde","es":"verde","en":["green"],"pos":"adjective","topic":"describing","note":"Same for both genders. Also means unripe."},
    {"id":"azul","es":"azul","en":["blue"],"pos":"adjective","topic":"describing","note":"Same for both genders. Plural azules."},
    {"id":"negro","es":"negro","en":["black"],"pos":"adjective","topic":"describing"},
    {"id":"blanco","es":"blanco","en":["white"],"pos":"adjective","topic":"describing","note":"Also a blank space."},
    {"id":"contento","es":"contento","en":["happy","pleased"],"pos":"adjective","topic":"feelings","note":"With estar, not ser: how you are now."},
    {"id":"enojado","es":"enojado","en":["angry"],"pos":"adjective","topic":"feelings","note":"Bravo also means angry in Colombia, not brave."},
    {"id":"preocupado","es":"preocupado","en":["worried"],"pos":"adjective","topic":"feelings","note":"preocuparse is to worry."},
    {"id":"nervioso","es":"nervioso","en":["nervous"],"pos":"adjective","topic":"feelings"},
    {"id":"aburrido","es":"aburrido","en":["bored","boring"],"pos":"adjective","topic":"feelings","note":"estar aburrido is bored; ser aburrido is boring. Worth getting right."},
    {"id":"enfermo","es":"enfermo","en":["ill","sick"],"pos":"adjective","topic":"body","note":"With estar."},
    {"id":"dolor","es":"dolor","en":["pain","ache"],"pos":"noun","topic":"body","note":"m. tengo dolor de cabeza is I have a headache."},
    {"id":"cabeza","es":"cabeza","en":["head"],"pos":"noun","topic":"body","note":"f."},
    {"id":"mano","es":"mano","en":["hand"],"pos":"noun","topic":"body","note":"f. despite ending in o: la mano."},
    {"id":"ojo","es":"ojo","en":["eye"],"pos":"noun","topic":"body","note":"m. ¡Ojo! on its own means watch out."},
    {"id":"pie","es":"pie","en":["foot"],"pos":"noun","topic":"body","note":"m. a pie means on foot."},
    {"id":"doler","es":"doler","en":["to hurt","to ache"],"pos":"verb","topic":"body","note":"Works like gustar: me duele, it hurts me."},
    {"id":"medico","es":"médico","en":["doctor"],"pos":"noun","topic":"body","note":"m. Doctor is also used, and is how you address them."},
    {"id":"uno","es":"uno","en":["one"],"pos":"number","topic":"numbers","note":"Shortens to un before a masculine noun: un café."},
    {"id":"dos","es":"dos","en":["two"],"pos":"number","topic":"numbers"},
    {"id":"tres","es":"tres","en":["three"],"pos":"number","topic":"numbers"},
    {"id":"cuatro","es":"cuatro","en":["four"],"pos":"number","topic":"numbers"},
    {"id":"cinco","es":"cinco","en":["five"],"pos":"number","topic":"numbers"},
    {"id":"diez","es":"diez","en":["ten"],"pos":"number","topic":"numbers"},
    {"id":"veinte","es":"veinte","en":["twenty"],"pos":"number","topic":"numbers"},
    {"id":"cien","es":"cien","en":["hundred"],"pos":"number","topic":"numbers","note":"cien exactly; ciento in 101 to 199."},
    {"id":"mil","es":"mil","en":["thousand"],"pos":"number","topic":"numbers","note":"Never un mil, just mil. You will use it constantly with pesos."},
    {"id":"primero","es":"primero","en":["first"],"pos":"adjective","topic":"numbers","note":"Shortens to primer before a masculine noun."},
    {"id":"ultimo","es":"último","en":["last"],"pos":"adjective","topic":"numbers","note":"The final one. pasado is last as in previous."},
    {"id":"medio","es":"medio","en":["half"],"pos":"adjective","topic":"numbers","note":"media hora is half an hour. mitad is the noun."},
    {"id":"ahora","es":"ahora","en":["now"],"pos":"adverb","topic":"time","note":"ahorita in Colombia can mean in a minute or just now, and is gloriously vague."},
    {"id":"hoy","es":"hoy","en":["today"],"pos":"adverb","topic":"time"},
    {"id":"manana","es":"mañana","en":["tomorrow","morning"],"pos":"noun","topic":"time","note":"Both. la mañana is the morning, mañana on its own is tomorrow."},
    {"id":"ayer","es":"ayer","en":["yesterday"],"pos":"adverb","topic":"time"},
    {"id":"noche","es":"noche","en":["night","evening"],"pos":"noun","topic":"time","note":"f. buenas noches is both good evening and good night."},
    {"id":"dia","es":"día","en":["day"],"pos":"noun","topic":"time","note":"m. despite the a: el día. todos los días is every day."},
    {"id":"semana","es":"semana","en":["week"],"pos":"noun","topic":"time","note":"f. fin de semana is weekend."},
    {"id":"mes","es":"mes","en":["month"],"pos":"noun","topic":"time","note":"m. Plural meses."},
    {"id":"ano","es":"año","en":["year"],"pos":"noun","topic":"time","note":"m. The ñ matters: ano without it is something else."},
    {"id":"hora","es":"hora","en":["hour","time"],"pos":"noun","topic":"time","note":"f. ¿Qué hora es? is what time is it."},
    {"id":"minuto","es":"minuto","en":["minute"],"pos":"noun","topic":"time","note":"m."},
    {"id":"temprano","es":"temprano","en":["early"],"pos":"adverb","topic":"time"},
    {"id":"tarde","es":"tarde","en":["late","afternoon"],"pos":"adverb","topic":"time","note":"Also a noun: la tarde, the afternoon. buenas tardes."},
    {"id":"proximo","es":"próximo","en":["next"],"pos":"adjective","topic":"time"},
    {"id":"pasado","es":"pasado","en":["last","past"],"pos":"adjective","topic":"time","note":"el año pasado is last year."},
    {"id":"lluvia","es":"lluvia","en":["rain"],"pos":"noun","topic":"nature","note":"f. llover is the verb: está lloviendo."},
    {"id":"sol","es":"sol","en":["sun","sunshine"],"pos":"noun","topic":"nature","note":"m. hace sol is it is sunny."},
    {"id":"clima","es":"clima","en":["weather","climate"],"pos":"noun","topic":"nature","note":"m. despite the a. Tiempo also means weather."},
    {"id":"rio","es":"río","en":["river"],"pos":"noun","topic":"nature","note":"m."},
    {"id":"montana","es":"montaña","en":["mountain"],"pos":"noun","topic":"nature","note":"f."},
    {"id":"playa","es":"playa","en":["beach"],"pos":"noun","topic":"nature","note":"f."},
    {"id":"arbol","es":"árbol","en":["tree"],"pos":"noun","topic":"nature","note":"m. Plural árboles."},
    {"id":"perro","es":"perro","en":["dog"],"pos":"noun","topic":"nature","note":"m. perra for a female, though it is also an insult."},
    {"id":"gato","es":"gato","en":["cat"],"pos":"noun","topic":"nature","note":"m. Also a car jack."},
    {"id":"por-favor","es":"por favor","en":["please"],"pos":"phrase","topic":"smalltalk"},
    {"id":"gracias","es":"gracias","en":["thank you","thanks"],"pos":"phrase","topic":"smalltalk","note":"Always plural. muchas gracias is thank you very much."},
    {"id":"perdon","es":"perdón","en":["sorry","excuse me"],"pos":"phrase","topic":"smalltalk","note":"For bumping into someone or interrupting. Lo siento is for real regret."},
    {"id":"hola","es":"hola","en":["hello","hi"],"pos":"phrase","topic":"smalltalk","note":"The h is silent."},
    {"id":"adios","es":"adiós","en":["goodbye"],"pos":"phrase","topic":"smalltalk","note":"Chao is far more common in Colombia."},
    {"id":"buenos-dias","es":"buenos días","en":["good morning"],"pos":"phrase","topic":"smalltalk","note":"Plural in Spanish. Buenas on its own works any time of day."},
    {"id":"con-permiso","es":"con permiso","en":["excuse me"],"pos":"phrase","topic":"smalltalk","note":"Said when leaving a room or squeezing past. Very Colombian."},
    {"id":"que-tal","es":"¿qué tal?","en":["how are you","how is it going"],"pos":"phrase","topic":"smalltalk","note":"Informal. ¿Qué más? is the Colombian version."},
    {"id":"vale-la-pena","es":"vale la pena","en":["it is worth it"],"pos":"phrase","topic":"smalltalk"}
  ],
  sentences: [
    {"id":"g0001","wordId":"hombre","es":"Ese {hombre} trabaja en la tienda.","answer":"hombre","en":"That man works in the shop."},
    {"id":"g0002","wordId":"mujer","es":"La {mujer} de la esquina vende arepas.","answer":"mujer","en":"The woman on the corner sells arepas."},
    {"id":"g0003","wordId":"nino","es":"El {niño} está jugando afuera.","answer":"niño","en":"The boy is playing outside."},
    {"id":"g0004","wordId":"nina","es":"La {niña} tiene siete años.","answer":"niña","en":"The girl is seven years old."},
    {"id":"g0005","wordId":"gente","es":"Hay mucha {gente} en el parque hoy.","answer":"gente","en":"There are a lot of people in the park today."},
    {"id":"g0006","wordId":"persona","es":"Solo falta una {persona} para empezar.","answer":"persona","en":"We are only one person short of starting."},
    {"id":"g0007","wordId":"amigo","es":"Mi {amigo} llega el martes.","answer":"amigo","en":"My friend arrives on Tuesday."},
    {"id":"g0008","wordId":"familia","es":"Toda mi {familia} vive en Bogotá.","answer":"familia","en":"My whole family lives in Bogotá."},
    {"id":"g0009","wordId":"madre","es":"Mi {madre} cocina muy bien.","answer":"madre","en":"My mother cooks very well."},
    {"id":"g0010","wordId":"padre","es":"Su {padre} es profesor.","answer":"padre","en":"His father is a teacher."},
    {"id":"g0011","wordId":"hijo","es":"Mi {hijo} empieza el colegio mañana.","answer":"hijo","en":"My son starts school tomorrow."},
    {"id":"g0012","wordId":"hermano","es":"Mi {hermano} vive en Medellín.","answer":"hermano","en":"My brother lives in Medellín."},
    {"id":"g0013","wordId":"hermana","es":"Mi {hermana} estudia medicina.","answer":"hermana","en":"My sister studies medicine."},
    {"id":"g0014","wordId":"esposo","es":"Su {esposo} trabaja de noche.","answer":"esposo","en":"Her husband works nights."},
    {"id":"g0015","wordId":"novio","es":"Ella vino con su {novio}.","answer":"novio","en":"She came with her boyfriend."},
    {"id":"g0016","wordId":"abuelo","es":"Mi {abuelo} tiene noventa años.","answer":"abuelo","en":"My grandfather is ninety."},
    {"id":"g0017","wordId":"senor","es":"Buenos días, {señor}.","answer":"señor","en":"Good morning, sir."},
    {"id":"g0018","wordId":"senora","es":"La {señora} preguntó por usted.","answer":"señora","en":"The lady asked for you."},
    {"id":"g0019","wordId":"vecino","es":"Mi {vecino} tiene dos perros.","answer":"vecino","en":"My neighbour has two dogs."},
    {"id":"g0020","wordId":"yo","es":"{Yo} no sabía nada de eso.","answer":"Yo","en":"I knew nothing about that."},
    {"id":"g0021","wordId":"el-pron","es":"{Él} llega tarde siempre.","answer":"Él","en":"He is always late."},
    {"id":"g0022","wordId":"ella","es":"{Ella} me llamó anoche.","answer":"Ella","en":"She called me last night."},
    {"id":"g0023","wordId":"ellos","es":"{Ellos} no vinieron a la reunión.","answer":"Ellos","en":"They did not come to the meeting."},
    {"id":"g0024","wordId":"usted","es":"¿{Usted} quiere algo de tomar?","answer":"Usted","en":"Would you like something to drink?"},
    {"id":"g0025","wordId":"ustedes","es":"¿{Ustedes} ya comieron?","answer":"Ustedes","en":"Have you all eaten?"},
    {"id":"g0026","wordId":"me","es":"{Me} llamo Juan.","answer":"Me","en":"My name is Juan."},
    {"id":"g0027","wordId":"te","es":"{Te} espero en la entrada.","answer":"Te","en":"I will wait for you at the entrance."},
    {"id":"g0028","wordId":"le","es":"{Le} di las llaves a mi hermana.","answer":"Le","en":"I gave the keys to my sister."},
    {"id":"g0029","wordId":"nos","es":"{Nos} vemos el viernes.","answer":"Nos","en":"See you on Friday."},
    {"id":"g0030","wordId":"su","es":"Olvidó {su} pasaporte en el hotel.","answer":"su","en":"He left his passport at the hotel."},
    {"id":"g0031","wordId":"ver","es":"No {veo} nada sin mis gafas.","answer":"veo","en":"I cannot see anything without my glasses."},
    {"id":"g0032","wordId":"pensar","es":"{Pienso} que tienes razón.","answer":"Pienso","en":"I think you are right."},
    {"id":"g0033","wordId":"creer","es":"{Creo} que va a llover.","answer":"Creo","en":"I think it is going to rain."},
    {"id":"g0034","wordId":"gustar","es":"Me {gusta} mucho esta ciudad.","answer":"gusta","en":"I like this city a lot."},
    {"id":"g0035","wordId":"empezar","es":"La película {empieza} a las ocho.","answer":"empieza","en":"The film starts at eight."},
    {"id":"g0036","wordId":"terminar","es":"{Termino} de trabajar a las seis.","answer":"Termino","en":"I finish work at six."},
    {"id":"g0037","wordId":"seguir","es":"{Sigo} estudiando español.","answer":"Sigo","en":"I am still studying Spanish."},
    {"id":"g0038","wordId":"volver","es":"{Vuelvo} en cinco minutos.","answer":"Vuelvo","en":"I will be back in five minutes."},
    {"id":"g0039","wordId":"llevar","es":"¿Puedo {llevar} esto a la mesa?","answer":"llevar","en":"Can I take this to the table?"},
    {"id":"g0040","wordId":"dejar","es":"{Dejé} las llaves en la casa.","answer":"Dejé","en":"I left the keys at home."},
    {"id":"g0041","wordId":"pasar","es":"¿Qué {pasa} contigo hoy?","answer":"pasa","en":"What is up with you today?"},
    {"id":"g0042","wordId":"quedar","es":"Solo {queda} un puesto libre.","answer":"queda","en":"There is only one free seat left."},
    {"id":"g0043","wordId":"parecer","es":"{Parece} que está cerrado.","answer":"Parece","en":"It seems that it is closed."},
    {"id":"g0044","wordId":"sentir","es":"Lo {siento}, no fue mi intención.","answer":"siento","en":"I am sorry, I did not mean to."},
    {"id":"g0045","wordId":"entender","es":"No {entiendo} lo que dice.","answer":"entiendo","en":"I do not understand what he is saying."},
    {"id":"g0046","wordId":"escribir","es":"Voy a {escribir} el correo ahora.","answer":"escribir","en":"I am going to write the email now."},
    {"id":"g0047","wordId":"leer","es":"Me gusta {leer} antes de dormir.","answer":"leer","en":"I like reading before sleeping."},
    {"id":"g0048","wordId":"escuchar","es":"{Escucho} música mientras trabajo.","answer":"Escucho","en":"I listen to music while I work."},
    {"id":"g0049","wordId":"mirar","es":"{Mira} ese edificio.","answer":"Mira","en":"Look at that building."},
    {"id":"g0050","wordId":"abrir","es":"¿A qué hora {abren} el banco?","answer":"abren","en":"What time do they open the bank?"},
    {"id":"g0051","wordId":"cerrar","es":"{Cierra} la puerta, por favor.","answer":"Cierra","en":"Close the door, please."},
    {"id":"g0052","wordId":"comprar","es":"Tengo que {comprar} pan.","answer":"comprar","en":"I have to buy bread."},
    {"id":"g0053","wordId":"vender","es":"Aquí {venden} frutas muy buenas.","answer":"venden","en":"They sell very good fruit here."},
    {"id":"g0054","wordId":"pagar","es":"¿Puedo {pagar} con tarjeta?","answer":"pagar","en":"Can I pay by card?"},
    {"id":"g0055","wordId":"ayudar","es":"¿Me puede {ayudar} con esto?","answer":"ayudar","en":"Can you help me with this?"},
    {"id":"g0056","wordId":"jugar","es":"Los niños {juegan} en el parque.","answer":"juegan","en":"The children play in the park."},
    {"id":"g0057","wordId":"cocinar","es":"Mi papá {cocina} los domingos.","answer":"cocina","en":"My dad cooks on Sundays."},
    {"id":"g0058","wordId":"correr","es":"{Corro} todas las mañanas.","answer":"Corro","en":"I run every morning."},
    {"id":"g0059","wordId":"llorar","es":"El bebé {llora} toda la noche.","answer":"llora","en":"The baby cries all night."},
    {"id":"g0060","wordId":"reir","es":"No te {rías} de mí.","answer":"rías","en":"Do not laugh at me."},
    {"id":"g0061","wordId":"olvidar","es":"No {olvides} tu paraguas.","answer":"olvides","en":"Do not forget your umbrella."},
    {"id":"g0062","wordId":"recordar","es":"No {recuerdo} su nombre.","answer":"recuerdo","en":"I do not remember his name."},
    {"id":"g0063","wordId":"cambiar","es":"Quiero {cambiar} de plan.","answer":"cambiar","en":"I want to change plan."},
    {"id":"g0064","wordId":"mandar","es":"Te {mando} la dirección por mensaje.","answer":"mando","en":"I will send you the address by message."},
    {"id":"g0065","wordId":"preguntar","es":"Voy a {preguntar} en la recepción.","answer":"preguntar","en":"I am going to ask at reception."},
    {"id":"g0066","wordId":"contestar","es":"Nadie {contesta} el teléfono.","answer":"contesta","en":"Nobody is answering the phone."},
    {"id":"g0067","wordId":"esperar-verbo","es":"Tuvimos que {aguardar} una hora.","answer":"aguardar","en":"We had to wait an hour."},
    {"id":"g0068","wordId":"intentar","es":"Voy a {intentar} otra vez.","answer":"intentar","en":"I am going to try again."},
    {"id":"g0069","wordId":"ganar","es":"Nuestro equipo {ganó} el partido.","answer":"ganó","en":"Our team won the match."},
    {"id":"g0070","wordId":"perder","es":"No quiero {perder} el vuelo.","answer":"perder","en":"I do not want to miss the flight."},
    {"id":"g0071","wordId":"y","es":"Quiero un café {y} un pan.","answer":"y","en":"I want a coffee and a bread roll."},
    {"id":"g0072","wordId":"o","es":"¿Prefieres té {o} café?","answer":"o","en":"Do you prefer tea or coffee?"},
    {"id":"g0073","wordId":"pero","es":"Es caro, {pero} vale la pena.","answer":"pero","en":"It is expensive, but it is worth it."},
    {"id":"g0074","wordId":"porque","es":"No salí {porque} estaba lloviendo.","answer":"porque","en":"I did not go out because it was raining."},
    {"id":"g0075","wordId":"si-cond","es":"{Si} llueve, nos quedamos en casa.","answer":"Si","en":"If it rains, we will stay at home."},
    {"id":"g0076","wordId":"que","es":"Creo {que} tiene razón.","answer":"que","en":"I think that he is right."},
    {"id":"g0077","wordId":"cuando","es":"Te llamo {cuando} llegue.","answer":"cuando","en":"I will call you when I arrive."},
    {"id":"g0078","wordId":"aunque","es":"Salimos {aunque} hacía frío.","answer":"aunque","en":"We went out although it was cold."},
    {"id":"g0079","wordId":"tambien","es":"Yo {también} quiero ir.","answer":"también","en":"I want to go too."},
    {"id":"g0080","wordId":"tampoco","es":"Yo {tampoco} lo sabía.","answer":"tampoco","en":"I did not know either."},
    {"id":"g0081","wordId":"muy","es":"El café está {muy} caliente.","answer":"muy","en":"The coffee is very hot."},
    {"id":"g0082","wordId":"mucho","es":"Hay {mucho} tráfico hoy.","answer":"mucho","en":"There is a lot of traffic today."},
    {"id":"g0083","wordId":"poco","es":"Solo hablo un {poco} de español.","answer":"poco","en":"I only speak a little Spanish."},
    {"id":"g0084","wordId":"mas","es":"¿Quieres {más} arroz?","answer":"más","en":"Do you want more rice?"},
    {"id":"g0085","wordId":"menos","es":"Hoy hay {menos} gente que ayer.","answer":"menos","en":"There are fewer people today than yesterday."},
    {"id":"g0086","wordId":"tanto","es":"No comas {tanto} antes de correr.","answer":"tanto","en":"Do not eat so much before running."},
    {"id":"g0087","wordId":"siempre","es":"{Siempre} desayuno a las siete.","answer":"Siempre","en":"I always have breakfast at seven."},
    {"id":"g0088","wordId":"nunca","es":"{Nunca} he estado en Cartagena.","answer":"Nunca","en":"I have never been to Cartagena."},
    {"id":"g0089","wordId":"ya","es":"{Ya} terminé el trabajo.","answer":"Ya","en":"I have already finished the work."},
    {"id":"g0090","wordId":"todavia","es":"{Todavía} no ha llegado.","answer":"Todavía","en":"He has not arrived yet."},
    {"id":"g0091","wordId":"tal-vez","es":"{Tal vez} vaya mañana.","answer":"Tal vez","en":"Maybe I will go tomorrow."},
    {"id":"g0092","wordId":"solo","es":"{Solo} queda uno.","answer":"Solo","en":"There is only one left."},
    {"id":"g0093","wordId":"bien","es":"Todo salió {bien}.","answer":"bien","en":"Everything went well."},
    {"id":"g0094","wordId":"mal","es":"Dormí {mal} anoche.","answer":"mal","en":"I slept badly last night."},
    {"id":"g0095","wordId":"asi","es":"Hazlo {así}.","answer":"así","en":"Do it like this."},
    {"id":"g0096","wordId":"como","es":"Trabaja {como} profesor.","answer":"como","en":"He works as a teacher."},
    {"id":"g0097","wordId":"sin","es":"Un café {sin} azúcar, por favor.","answer":"sin","en":"A coffee without sugar, please."},
    {"id":"g0098","wordId":"con","es":"Voy {con} mi hermana.","answer":"con","en":"I am going with my sister."},
    {"id":"g0099","wordId":"sobre","es":"Hablamos {sobre} el proyecto.","answer":"sobre","en":"We talked about the project."},
    {"id":"g0100","wordId":"entre","es":"La tienda está {entre} el banco y la farmacia.","answer":"entre","en":"The shop is between the bank and the chemist."},
    {"id":"g0101","wordId":"hasta","es":"Trabajo {hasta} las seis.","answer":"hasta","en":"I work until six."},
    {"id":"g0102","wordId":"durante","es":"Llovió {durante} toda la noche.","answer":"durante","en":"It rained all night long."},
    {"id":"g0103","wordId":"antes","es":"Llegué {antes} que tú.","answer":"antes","en":"I arrived before you."},
    {"id":"g0104","wordId":"despues","es":"Hablamos {después} de la reunión.","answer":"después","en":"We will talk after the meeting."},
    {"id":"g0105","wordId":"nada","es":"No hay {nada} en la nevera.","answer":"nada","en":"There is nothing in the fridge."},
    {"id":"g0106","wordId":"nadie","es":"{Nadie} me avisó.","answer":"Nadie","en":"Nobody told me."},
    {"id":"g0107","wordId":"algo","es":"¿Quieres tomar {algo}?","answer":"algo","en":"Do you want something to drink?"},
    {"id":"g0108","wordId":"alguien","es":"{Alguien} dejó esto aquí.","answer":"Alguien","en":"Somebody left this here."},
    {"id":"g0109","wordId":"todo","es":"{Todo} está listo.","answer":"Todo","en":"Everything is ready."},
    {"id":"g0110","wordId":"otro","es":"Dame {otro}, por favor.","answer":"otro","en":"Give me another one, please."},
    {"id":"g0111","wordId":"cada","es":"{Cada} día es distinto.","answer":"Cada","en":"Every day is different."},
    {"id":"g0112","wordId":"mientras","es":"Leo {mientras} espero.","answer":"mientras","en":"I read while I wait."},
    {"id":"g0113","wordId":"claro","es":"{Claro} que puedes venir.","answer":"Claro","en":"Of course you can come."},
    {"id":"g0114","wordId":"casa","es":"Mi {casa} queda cerca del parque.","answer":"casa","en":"My house is near the park."},
    {"id":"g0115","wordId":"puerta","es":"Cierra la {puerta} con llave.","answer":"puerta","en":"Lock the door."},
    {"id":"g0116","wordId":"ventana","es":"Abre la {ventana}, hace calor.","answer":"ventana","en":"Open the window, it is hot."},
    {"id":"g0117","wordId":"llave","es":"Perdí la {llave} del apartamento.","answer":"llave","en":"I lost the key to the flat."},
    {"id":"g0118","wordId":"silla","es":"Esa {silla} está rota.","answer":"silla","en":"That chair is broken."},
    {"id":"g0119","wordId":"cocina","es":"La {cocina} es la parte más grande de la casa.","answer":"cocina","en":"The kitchen is the biggest part of the house."},
    {"id":"g0120","wordId":"ropa","es":"Tengo que lavar la {ropa}.","answer":"ropa","en":"I have to wash the clothes."},
    {"id":"g0121","wordId":"luz","es":"Apaga la {luz} cuando salgas.","answer":"luz","en":"Turn off the light when you leave."},
    {"id":"g0122","wordId":"pan","es":"Compré {pan} fresco esta mañana.","answer":"pan","en":"I bought fresh bread this morning."},
    {"id":"g0123","wordId":"arroz","es":"El almuerzo viene con {arroz} y frijoles.","answer":"arroz","en":"Lunch comes with rice and beans."},
    {"id":"g0124","wordId":"carne","es":"No como {carne} los lunes.","answer":"carne","en":"I do not eat meat on Mondays."},
    {"id":"g0125","wordId":"pollo","es":"Voy a pedir {pollo} con papas.","answer":"pollo","en":"I am going to order chicken with potatoes."},
    {"id":"g0126","wordId":"huevo","es":"Quiero un {huevo} frito.","answer":"huevo","en":"I want a fried egg."},
    {"id":"g0127","wordId":"fruta","es":"La {fruta} aquí es muy barata.","answer":"fruta","en":"The fruit here is very cheap."},
    {"id":"g0128","wordId":"leche","es":"El café con {leche} me gusta más.","answer":"leche","en":"I prefer coffee with milk."},
    {"id":"g0129","wordId":"cerveza","es":"Dos {cervezas} bien frías, por favor.","answer":"cervezas","en":"Two very cold beers, please."},
    {"id":"g0130","wordId":"jugo","es":"Un {jugo} de mango, por favor.","answer":"jugo","en":"A mango juice, please."},
    {"id":"g0131","wordId":"azucar","es":"Sin {azúcar}, gracias.","answer":"azúcar","en":"Without sugar, thanks."},
    {"id":"g0132","wordId":"sal","es":"Le falta {sal} a la sopa.","answer":"sal","en":"The soup needs salt."},
    {"id":"g0133","wordId":"sopa","es":"La {sopa} está muy caliente todavía.","answer":"sopa","en":"The soup is still very hot."},
    {"id":"g0134","wordId":"desayuno","es":"El {desayuno} está incluido.","answer":"desayuno","en":"Breakfast is included."},
    {"id":"g0135","wordId":"almuerzo","es":"El {almuerzo} del día cuesta doce mil.","answer":"almuerzo","en":"The set lunch costs twelve thousand."},
    {"id":"g0136","wordId":"cena","es":"La {cena} es a las ocho.","answer":"cena","en":"Dinner is at eight."},
    {"id":"g0137","wordId":"cuenta","es":"¿Nos trae la {cuenta}, por favor?","answer":"cuenta","en":"Could you bring us the bill, please?"},
    {"id":"g0138","wordId":"dinero","es":"No tengo {dinero} en efectivo.","answer":"dinero","en":"I do not have any cash."},
    {"id":"g0139","wordId":"plata","es":"No me alcanza la {plata}.","answer":"plata","en":"I do not have enough money."},
    {"id":"g0140","wordId":"precio","es":"¿Cuál es el {precio} sin descuento?","answer":"precio","en":"What is the price without the discount?"},
    {"id":"g0141","wordId":"tienda","es":"Voy a la {tienda} por leche.","answer":"tienda","en":"I am going to the shop for milk."},
    {"id":"g0142","wordId":"mercado","es":"El {mercado} abre los sábados.","answer":"mercado","en":"The market opens on Saturdays."},
    {"id":"g0143","wordId":"ciudad","es":"Esta {ciudad} me encanta.","answer":"ciudad","en":"I love this city."},
    {"id":"g0144","wordId":"pais","es":"¿De qué {país} eres?","answer":"país","en":"What country are you from?"},
    {"id":"g0145","wordId":"mundo","es":"Quiero viajar por todo el {mundo}.","answer":"mundo","en":"I want to travel all over the world."},
    {"id":"g0146","wordId":"lugar","es":"Es un buen {lugar} para comer.","answer":"lugar","en":"It is a good place to eat."},
    {"id":"g0147","wordId":"carro","es":"Dejé el {carro} en el parqueadero.","answer":"carro","en":"I left the car in the car park."},
    {"id":"g0148","wordId":"bus","es":"El {bus} pasa cada diez minutos.","answer":"bus","en":"The bus comes every ten minutes."},
    {"id":"g0149","wordId":"avion","es":"El {avión} sale a las seis de la mañana.","answer":"avión","en":"The plane leaves at six in the morning."},
    {"id":"g0150","wordId":"viaje","es":"El {viaje} dura ocho horas.","answer":"viaje","en":"The journey takes eight hours."},
    {"id":"g0151","wordId":"maleta","es":"Mi {maleta} no llegó.","answer":"maleta","en":"My suitcase did not arrive."},
    {"id":"g0152","wordId":"boleto","es":"Compré el {boleto} por internet.","answer":"boleto","en":"I bought the ticket online."},
    {"id":"g0153","wordId":"hotel","es":"El {hotel} queda en el centro.","answer":"hotel","en":"The hotel is in the centre."},
    {"id":"g0154","wordId":"aeropuerto","es":"Llegamos al {aeropuerto} muy temprano.","answer":"aeropuerto","en":"We got to the airport very early."},
    {"id":"g0155","wordId":"trabajo","es":"Tengo mucho {trabajo} esta semana.","answer":"trabajo","en":"I have a lot of work this week."},
    {"id":"g0156","wordId":"oficina","es":"La {oficina} cierra a las cinco.","answer":"oficina","en":"The office closes at five."},
    {"id":"g0157","wordId":"empresa","es":"Trabajo en una {empresa} de energía.","answer":"empresa","en":"I work at an energy company."},
    {"id":"g0158","wordId":"reunion","es":"La {reunión} se movió para el jueves.","answer":"reunión","en":"The meeting was moved to Thursday."},
    {"id":"g0159","wordId":"jefe","es":"Mi {jefe} está de viaje.","answer":"jefe","en":"My boss is away."},
    {"id":"g0160","wordId":"estudiar","es":"{Estudio} ingeniería.","answer":"Estudio","en":"I study engineering."},
    {"id":"g0161","wordId":"clase","es":"La {clase} empieza a las nueve.","answer":"clase","en":"The class starts at nine."},
    {"id":"g0162","wordId":"palabra","es":"No conozco esa {palabra}.","answer":"palabra","en":"I do not know that word."},
    {"id":"g0163","wordId":"pregunta","es":"Tengo una {pregunta} sobre el horario.","answer":"pregunta","en":"I have a question about the timetable."},
    {"id":"g0164","wordId":"problema","es":"No hay ningún {problema}.","answer":"problema","en":"There is no problem at all."},
    {"id":"g0165","wordId":"cosa","es":"Tengo una {cosa} que contarte.","answer":"cosa","en":"I have something to tell you."},
    {"id":"g0166","wordId":"bueno","es":"Es un {buen} restaurante.","answer":"buen","en":"It is a good restaurant."},
    {"id":"g0167","wordId":"malo","es":"Hoy tuve un día {malo}.","answer":"malo","en":"I had a bad day today."},
    {"id":"g0168","wordId":"grande","es":"Necesito una maleta más {grande}.","answer":"grande","en":"I need a bigger suitcase."},
    {"id":"g0169","wordId":"pequeno","es":"Vivo en un apartamento {pequeño}.","answer":"pequeño","en":"I live in a small flat."},
    {"id":"g0170","wordId":"nuevo","es":"Compré un carro {nuevo}.","answer":"nuevo","en":"I bought a new car."},
    {"id":"g0171","wordId":"viejo","es":"Ese edificio es muy {viejo}.","answer":"viejo","en":"That building is very old."},
    {"id":"g0172","wordId":"joven","es":"Es demasiado {joven} para manejar.","answer":"joven","en":"He is too young to drive."},
    {"id":"g0173","wordId":"largo","es":"El camino es más {largo} de lo que pensaba.","answer":"largo","en":"The road is longer than I thought."},
    {"id":"g0174","wordId":"corto","es":"Fue una reunión {corta}.","answer":"corta","en":"It was a short meeting."},
    {"id":"g0175","wordId":"alto","es":"Mi hermano es muy {alto}.","answer":"alto","en":"My brother is very tall."},
    {"id":"g0176","wordId":"bajo","es":"El techo es muy {bajo}.","answer":"bajo","en":"The ceiling is very low."},
    {"id":"g0177","wordId":"caro","es":"Ese hotel es demasiado {caro}.","answer":"caro","en":"That hotel is too expensive."},
    {"id":"g0178","wordId":"barato","es":"Encontré un vuelo {barato}.","answer":"barato","en":"I found a cheap flight."},
    {"id":"g0179","wordId":"facil","es":"El examen fue más {fácil} de lo esperado.","answer":"fácil","en":"The exam was easier than expected."},
    {"id":"g0180","wordId":"dificil","es":"Es {difícil} entenderlo al principio.","answer":"difícil","en":"It is hard to understand at first."},
    {"id":"g0181","wordId":"rapido","es":"Necesito una respuesta {rápida}.","answer":"rápida","en":"I need a quick answer."},
    {"id":"g0182","wordId":"lento","es":"El internet está muy {lento} hoy.","answer":"lento","en":"The internet is very slow today."},
    {"id":"g0183","wordId":"caliente","es":"El agua está {caliente}.","answer":"caliente","en":"The water is hot."},
    {"id":"g0184","wordId":"frio","es":"La cerveza está bien {fría}.","answer":"fría","en":"The beer is nice and cold."},
    {"id":"g0185","wordId":"limpio","es":"El cuarto ya está {limpio}.","answer":"limpio","en":"The room is clean now."},
    {"id":"g0186","wordId":"sucio","es":"Estos platos están {sucios}.","answer":"sucios","en":"These plates are dirty."},
    {"id":"g0187","wordId":"bonito","es":"Qué vista tan {bonita}.","answer":"bonita","en":"What a lovely view."},
    {"id":"g0188","wordId":"feo","es":"El clima está {feo} hoy.","answer":"feo","en":"The weather is nasty today."},
    {"id":"g0189","wordId":"importante","es":"Es {importante} llegar a tiempo.","answer":"importante","en":"It is important to arrive on time."},
    {"id":"g0190","wordId":"posible","es":"¿Es {posible} cambiar la fecha?","answer":"posible","en":"Is it possible to change the date?"},
    {"id":"g0191","wordId":"seguro","es":"No estoy {seguro} de la dirección.","answer":"seguro","en":"I am not sure of the address."},
    {"id":"g0192","wordId":"amarillo","es":"El taxi {amarillo} está esperando.","answer":"amarillo","en":"The yellow taxi is waiting."},
    {"id":"g0193","wordId":"rojo","es":"Prefiero el vino {rojo}.","answer":"rojo","en":"I prefer red wine."},
    {"id":"g0194","wordId":"verde","es":"El semáforo está en {verde}.","answer":"verde","en":"The light is green."},
    {"id":"g0195","wordId":"azul","es":"Tiene los ojos {azules}.","answer":"azules","en":"He has blue eyes."},
    {"id":"g0196","wordId":"negro","es":"Me gusta el café {negro}.","answer":"negro","en":"I like black coffee."},
    {"id":"g0197","wordId":"blanco","es":"Necesito una hoja en {blanco}.","answer":"blanco","en":"I need a blank sheet of paper."},
    {"id":"g0198","wordId":"contento","es":"Estoy muy {contento} con el resultado.","answer":"contento","en":"I am very pleased with the result."},
    {"id":"g0199","wordId":"enojado","es":"Está {enojado} conmigo.","answer":"enojado","en":"He is angry with me."},
    {"id":"g0200","wordId":"preocupado","es":"Estoy {preocupada} por el examen.","answer":"preocupada","en":"I am worried about the exam."},
    {"id":"g0201","wordId":"nervioso","es":"Me pongo {nervioso} antes de hablar.","answer":"nervioso","en":"I get nervous before speaking."},
    {"id":"g0202","wordId":"aburrido","es":"La película estuvo {aburrida}.","answer":"aburrida","en":"The film was boring."},
    {"id":"g0203","wordId":"enfermo","es":"No fui a trabajar porque estaba {enfermo}.","answer":"enfermo","en":"I did not go to work because I was ill."},
    {"id":"g0204","wordId":"dolor","es":"Tengo un {dolor} en la espalda.","answer":"dolor","en":"I have a pain in my back."},
    {"id":"g0205","wordId":"cabeza","es":"Me duele la {cabeza}.","answer":"cabeza","en":"My head hurts."},
    {"id":"g0206","wordId":"mano","es":"Dame la {mano}.","answer":"mano","en":"Give me your hand."},
    {"id":"g0207","wordId":"ojo","es":"Me entró algo en el {ojo}.","answer":"ojo","en":"Something got in my eye."},
    {"id":"g0208","wordId":"pie","es":"Vamos a {pie}, queda cerca.","answer":"pie","en":"Let us walk, it is nearby."},
    {"id":"g0209","wordId":"doler","es":"Me {duelen} las piernas.","answer":"duelen","en":"My legs hurt."},
    {"id":"g0210","wordId":"medico","es":"Tengo cita con el {médico} mañana.","answer":"médico","en":"I have an appointment with the doctor tomorrow."},
    {"id":"g0211","wordId":"uno","es":"Solo queda {uno}.","answer":"uno","en":"There is only one left."},
    {"id":"g0212","wordId":"dos","es":"Quiero {dos} tintos, por favor.","answer":"dos","en":"I want two black coffees, please."},
    {"id":"g0213","wordId":"tres","es":"Llegamos en {tres} horas.","answer":"tres","en":"We arrive in three hours."},
    {"id":"g0214","wordId":"cuatro","es":"Somos {cuatro} personas.","answer":"cuatro","en":"There are four of us."},
    {"id":"g0215","wordId":"cinco","es":"Nos vemos a las {cinco}.","answer":"cinco","en":"See you at five."},
    {"id":"g0216","wordId":"diez","es":"Cuesta {diez} mil pesos.","answer":"diez","en":"It costs ten thousand pesos."},
    {"id":"g0217","wordId":"veinte","es":"Tengo {veinte} minutos libres.","answer":"veinte","en":"I have twenty minutes free."},
    {"id":"g0218","wordId":"cien","es":"Hay más de {cien} personas.","answer":"cien","en":"There are more than a hundred people."},
    {"id":"g0219","wordId":"mil","es":"El almuerzo cuesta quince {mil}.","answer":"mil","en":"Lunch costs fifteen thousand."},
    {"id":"g0220","wordId":"primero","es":"Es la {primera} vez que vengo.","answer":"primera","en":"It is the first time I have come."},
    {"id":"g0221","wordId":"ultimo","es":"Este es el {último} bus.","answer":"último","en":"This is the last bus."},
    {"id":"g0222","wordId":"medio","es":"Espérame {media} hora.","answer":"media","en":"Wait half an hour for me."},
    {"id":"g0223","wordId":"ahora","es":"{Ahora} no puedo hablar.","answer":"Ahora","en":"I cannot talk now."},
    {"id":"g0224","wordId":"hoy","es":"{Hoy} no trabajo.","answer":"Hoy","en":"I am not working today."},
    {"id":"g0225","wordId":"manana","es":"Te veo {mañana} temprano.","answer":"mañana","en":"I will see you early tomorrow."},
    {"id":"g0226","wordId":"ayer","es":"{Ayer} estuve en la oficina.","answer":"Ayer","en":"I was at the office yesterday."},
    {"id":"g0227","wordId":"noche","es":"Anoche no dormí en toda la {noche}.","answer":"noche","en":"Last night I did not sleep all night."},
    {"id":"g0228","wordId":"dia","es":"Fue un {día} muy largo.","answer":"día","en":"It was a very long day."},
    {"id":"g0229","wordId":"semana","es":"La {semana} pasada estuve enfermo.","answer":"semana","en":"Last week I was ill."},
    {"id":"g0230","wordId":"mes","es":"El próximo {mes} viajo a Perú.","answer":"mes","en":"Next month I am travelling to Peru."},
    {"id":"g0231","wordId":"ano","es":"Llevo un {año} aquí.","answer":"año","en":"I have been here a year."},
    {"id":"g0232","wordId":"hora","es":"La {hora} de salida es a las tres.","answer":"hora","en":"The departure time is at three."},
    {"id":"g0233","wordId":"minuto","es":"Dame un {minuto}.","answer":"minuto","en":"Give me a minute."},
    {"id":"g0234","wordId":"temprano","es":"Me levanto muy {temprano}.","answer":"temprano","en":"I get up very early."},
    {"id":"g0235","wordId":"tarde","es":"Llegué {tarde} a la reunión.","answer":"tarde","en":"I arrived late to the meeting."},
    {"id":"g0236","wordId":"proximo","es":"El {próximo} tren sale en veinte minutos.","answer":"próximo","en":"The next train leaves in twenty minutes."},
    {"id":"g0237","wordId":"pasado","es":"El mes {pasado} llovió mucho.","answer":"pasado","en":"Last month it rained a lot."},
    {"id":"g0238","wordId":"lluvia","es":"La {lluvia} no paró en toda la tarde.","answer":"lluvia","en":"The rain did not stop all afternoon."},
    {"id":"g0239","wordId":"sol","es":"Hoy hay mucho {sol}.","answer":"sol","en":"It is very sunny today."},
    {"id":"g0240","wordId":"clima","es":"El {clima} aquí cambia cada hora.","answer":"clima","en":"The weather here changes every hour."},
    {"id":"g0241","wordId":"rio","es":"Nadamos en el {río} el domingo.","answer":"río","en":"We swam in the river on Sunday."},
    {"id":"g0242","wordId":"montana","es":"La {montaña} se ve desde la ventana.","answer":"montaña","en":"The mountain is visible from the window."},
    {"id":"g0243","wordId":"playa","es":"Pasamos el día en la {playa}.","answer":"playa","en":"We spent the day at the beach."},
    {"id":"g0244","wordId":"arbol","es":"Hay un {árbol} enorme en el patio.","answer":"árbol","en":"There is an enormous tree in the yard."},
    {"id":"g0245","wordId":"perro","es":"El {perro} del vecino ladra toda la noche.","answer":"perro","en":"The neighbour's dog barks all night."},
    {"id":"g0246","wordId":"gato","es":"Mi {gato} duerme todo el día.","answer":"gato","en":"My cat sleeps all day."},
    {"id":"g0247","wordId":"por-favor","es":"Un tinto, {por favor}.","answer":"por favor","en":"A black coffee, please."},
    {"id":"g0248","wordId":"gracias","es":"Muchas {gracias} por la ayuda.","answer":"gracias","en":"Thank you very much for the help."},
    {"id":"g0249","wordId":"perdon","es":"{Perdón}, ¿me dejas pasar?","answer":"Perdón","en":"Excuse me, can I get past?"},
    {"id":"g0250","wordId":"hola","es":"{Hola}, ¿cómo estás?","answer":"Hola","en":"Hello, how are you?"},
    {"id":"g0251","wordId":"adios","es":"{Adiós}, nos vemos pronto.","answer":"Adiós","en":"Goodbye, see you soon."},
    {"id":"g0252","wordId":"buenos-dias","es":"{Buenos días}, ¿en qué le puedo ayudar?","answer":"Buenos días","en":"Good morning, how can I help you?"},
    {"id":"g0253","wordId":"con-permiso","es":"{Con permiso}, ya me voy.","answer":"Con permiso","en":"Excuse me, I am off now."},
    {"id":"g0254","wordId":"que-tal","es":"{¿Qué tal?} ¿Cómo va todo?","answer":"¿Qué tal?","en":"How is it going? How is everything?"},
    {"id":"g0255","wordId":"vale-la-pena","es":"El viaje es largo pero {vale la pena}.","answer":"vale la pena","en":"The journey is long but it is worth it."},
    {"id":"g0256","wordId":"dormitorio","es":"El {dormitorio} tiene una ventana grande.","answer":"dormitorio","en":"The bedroom has a big window."},
    {"id":"g0257","wordId":"plato","es":"¿Me trae otro {plato}, por favor?","answer":"plato","en":"Could you bring me another plate, please?"},
    {"id":"g0258","wordId":"vaso-de-agua","es":"¿Me regala un {vaso de agua}?","answer":"vaso de agua","en":"Could I have a glass of water?"},
    {"id":"g0259","wordId":"copa-vino","es":"Pedimos una {copa de vino} tinto.","answer":"copa de vino","en":"We ordered a glass of red wine."},
    {"id":"g0260","wordId":"cambio","es":"No tengo {cambio} de cincuenta mil.","answer":"cambio","en":"I do not have change for fifty thousand."},
    {"id":"g0261","wordId":"punto","es":"Ese es un buen {punto}.","answer":"punto","en":"That is a good point."},
    {"id":"g0262","wordId":"pinta","es":"Nos tomamos una {pinta} después del trabajo.","answer":"pinta","en":"We had a pint after work."},
    {"id":"g0263","wordId":"camino","es":"El {camino} al pueblo está cerrado.","answer":"camino","en":"The road to the village is closed."},
    {"id":"g0264","wordId":"nuestro","es":"{Nuestro} vuelo sale a las diez.","answer":"Nuestro","en":"Our flight leaves at ten."},
    {"id":"g0265","wordId":"mi","es":"Esta es {mi} maleta.","answer":"mi","en":"This is my suitcase."},
    {"id":"g0266","wordId":"tu","es":"¿Dónde está {tu} carro?","answer":"tu","en":"Where is your car?"},
    {"id":"g0267","wordId":"debil","es":"La señal está muy {débil} aquí.","answer":"débil","en":"The signal is very weak here."},
    {"id":"g0268","wordId":"pleno","es":"Se cayó en {pleno} centro de la ciudad.","answer":"pleno","en":"He fell right in the middle of the city centre."},
    {"id":"g0269","wordId":"enfrente","es":"El banco está {enfrente} de la iglesia.","answer":"enfrente","en":"The bank is opposite the church."},
    {"id":"g0270","wordId":"martes","es":"Nos vemos el {martes} en la tarde.","answer":"martes","en":"See you on Tuesday afternoon."},
    {"id":"g0271","wordId":"miercoles","es":"El {miércoles} tengo clase de español.","answer":"miércoles","en":"On Wednesday I have a Spanish class."},
    {"id":"g0272","wordId":"jueves","es":"Todos los {jueves} voy al gimnasio.","answer":"jueves","en":"Every Thursday I go to the gym."},
    {"id":"g0273","wordId":"sabado","es":"El {sábado} no trabajo.","answer":"sábado","en":"I do not work on Saturday."},
    {"id":"g0274","wordId":"cuantos","es":"¿{Cuántos} años tienes?","answer":"Cuántos","en":"How old are you?"},
    {"id":"g0275","wordId":"por-cuanto-tiempo","es":"¿{Por cuánto tiempo} se queda en Colombia?","answer":"Por cuánto tiempo","en":"How long are you staying in Colombia?"},
    {"id":"g0276","wordId":"alguna","es":"¿Tienes {alguna} pregunta?","answer":"alguna","en":"Do you have any questions?"},
    {"id":"g0277","wordId":"asimismo","es":"El precio subió; {asimismo} bajó la calidad.","answer":"asimismo","en":"The price went up; furthermore the quality went down."},
    {"id":"g0278","wordId":"esto","es":"¿Qué es {esto}?","answer":"esto","en":"What is this?"},
    {"id":"g0279","wordId":"eso","es":"{Eso} no me parece bien.","answer":"Eso","en":"That does not seem right to me."},
    {"id":"g0280","wordId":"cuanto-cuesta","es":"¿{Cuánto cuesta} el almuerzo del día?","answer":"Cuánto cuesta","en":"How much is the set lunch?"},
    {"id":"g0281","wordId":"cuanto-tiempo","es":"¿{Cuánto tiempo} dura el viaje?","answer":"Cuánto tiempo","en":"How long does the journey take?"},
    {"id":"g0282","wordId":"buena-suerte","es":"{Buena suerte} con el examen.","answer":"Buena suerte","en":"Good luck with the exam."},
    {"id":"g0283","wordId":"que-quieres","es":"¿{Qué quieres} tomar?","answer":"Qué quieres","en":"What do you want to drink?"},
    {"id":"g0284","wordId":"llamando","es":"Te estuve {llamando} toda la mañana.","answer":"llamando","en":"I was calling you all morning."},
    {"id":"g0285","wordId":"siguiente-en-la-fila","es":"Soy el {siguiente en la fila}.","answer":"siguiente en la fila","en":"I am next in the queue."}
  ],
};

window.VOCAB = VOCAB;
